USE oltp_commerce
GO

INSERT INTO supplier VALUES('EDITORA LELIVROS')
INSERT INTO supplier VALUES('EDITORA MUNDO FANTASIA')
INSERT INTO supplier VALUES('EDITORA AMAZONIA')
INSERT INTO supplier VALUES('STUDIOS HB')
INSERT INTO supplier VALUES('STUDIOS HOLLYWOOD')
INSERT INTO supplier VALUES('STUDIOS CALIFORNIA')
INSERT INTO supplier VALUES('EM SPORTS')
INSERT INTO supplier VALUES('BILLZAR GAMES')
INSERT INTO supplier VALUES('BRAZUCA JOGOS')
INSERT INTO supplier VALUES('JOGAR GAMES')
INSERT INTO supplier VALUES('MOTOROLA') --
INSERT INTO supplier VALUES('NOKIA') --
INSERT INTO supplier VALUES('SAMSUNG') --
INSERT INTO supplier VALUES('LG') --
INSERT INTO supplier VALUES('DREAMC') --
INSERT INTO supplier VALUES('GFORCE') --
INSERT INTO supplier VALUES('APPLE') --
INSERT INTO supplier VALUES('SONY') --
INSERT INTO supplier VALUES('WALLITA') --
INSERT INTO supplier VALUES('ARNO') --
INSERT INTO supplier VALUES('MULTILASER') --
INSERT INTO supplier VALUES('MICROSOFT') --
INSERT INTO supplier VALUES('ACER') --
INSERT INTO supplier VALUES('VISION') --
INSERT INTO supplier VALUES('PHILIPS')
INSERT INTO supplier VALUES('SANDISK') --
INSERT INTO supplier VALUES('BRASTEMP') --
INSERT INTO supplier VALUES('GANCA') --
INSERT INTO supplier VALUES('BRITANIA') --
INSERT INTO supplier VALUES('MOVEIS VAREJÃO')
INSERT INTO supplier VALUES('BRASIL MADEIRAS')
INSERT INTO supplier VALUES('LINHAS AREAS BRAZUCA')
INSERT INTO supplier VALUES('LINHAS BRASIL EXPRESS')
INSERT INTO supplier VALUES('LINHAS LATINAS DE AVIÕES')
INSERT INTO supplier VALUES('LINHAS INTERNACIONAIS EURO')
INSERT INTO supplier VALUES('AMERICA LINES EXPRESS')
INSERT INTO supplier VALUES('LENOVO')
INSERT INTO supplier VALUES('CCE')
INSERT INTO supplier VALUES('PANASONIC')
INSERT INTO supplier VALUES('GENIUS')
INSERT INTO supplier VALUES('HP')
GO

SELECT * FROM supplier