USE oltp_commerce
GO

INSERT INTO method_of_payment VALUES('Tranferência - Vista')
INSERT INTO method_of_payment VALUES('Depósito - Vista')
INSERT INTO method_of_payment VALUES('Boleto - Vista')
INSERT INTO method_of_payment VALUES('Cartão Master - Vencimento')
INSERT INTO method_of_payment VALUES('Cartão Master 2 vezes')
INSERT INTO method_of_payment VALUES('Cartão Master 3 vezes')
INSERT INTO method_of_payment VALUES('Cartão Master 4 vezes')
INSERT INTO method_of_payment VALUES('Cartão Master 5 vezes')
INSERT INTO method_of_payment VALUES('Cartão Master 10 vezes')
INSERT INTO method_of_payment VALUES('Cartão Visa - Vencimento')
INSERT INTO method_of_payment VALUES('Cartão Visa 2 vezes')
INSERT INTO method_of_payment VALUES('Cartão Visa 3 vezes')
INSERT INTO method_of_payment VALUES('Cartão Visa 4 vezes')
INSERT INTO method_of_payment VALUES('Cartão Visa 5 vezes')
INSERT INTO method_of_payment VALUES('Cartão Visa 10 vezes')
INSERT INTO method_of_payment VALUES('Cartão American - Vencimento')
INSERT INTO method_of_payment VALUES('Cartão American 5 vezes')
INSERT INTO method_of_payment VALUES('Cartão American 10 vezes')
INSERT INTO method_of_payment VALUES('Cartão American 12 vezes')
INSERT INTO method_of_payment VALUES('Pay Pall - Vista')
INSERT INTO method_of_payment VALUES('Cartão Visa 2 vezes')
INSERT INTO method_of_payment VALUES('Cartão Visa 3 vezes')
INSERT INTO method_of_payment VALUES('Cartão Visa 4 vezes')
INSERT INTO method_of_payment VALUES('Pay Pall - 5 vezes')
INSERT INTO method_of_payment VALUES('Pay Pall - 12 vezes')
INSERT INTO method_of_payment VALUES('Pagamento Seguro Web - Vista')
GO