
CREATE PROCEDURE REG_INVOICES AS
DECLARE
	C_INVOICE CURSOR FOR
	SELECT number FROM invoice
	WHERE number NOT IN(SELECT id_invoice FROM invoice_item)

DECLARE
	@ID_PRODUCT INT,
	@ID_INVOICE INT,
	@TOTAL NUMERIC(10,2)

OPEN C_INVOICE
FETCH NEXT FROM C_INVOICE
INTO @ID_INVOICE

WHILE @@FETCH_STATUS = 0
BEGIN

	SET @ID_PRODUCT = (SELECT TOP 1 id_product FROM product ORDER BY NEWID())
	SET @TOTAL = (SELECT price FROM product WHERE id_product = @ID_PRODUCT)

	INSERT INTO
		invoice_item(id_product, id_invoice, quantity, total_value_item)
	VALUES
		(@ID_PRODUCT, @ID_INVOICE, 1, @TOTAL)

FETCH NEXT FROM C_INVOICE
INTO @ID_INVOICE
END

CLOSE C_INVOICE
DEALLOCATE C_INVOICE
GO