USE oltp_commerce
GO

SELECT * FROM seller
GO

INSERT INTO seller VALUES('EDUARDO SANTOS','M','ESANTOS.MANAGER@TERA.COM',NULL)
INSERT INTO seller VALUES('RENATA MONTEIRO','F','RMONT@TERA.COM',1)
INSERT INTO seller VALUES('JOAO NUNES','M','JNUNES@TERA.COM',1)
INSERT INTO seller VALUES('CLARA MAFRA','F','CMAFRA@TERA.COM',1)
INSERT INTO seller VALUES('GERALDO FRANCISCO','M','GFRANCISCO@TERA.COM',1)
INSERT INTO seller VALUES('RODRIGO BIO','M','RBIO@TERA.COM',1)
INSERT INTO seller VALUES('SERGIO AGUDO','M','SAGUDO@TERA.COM',1)
INSERT INTO seller VALUES('PILAR SANCHES','F','PSANCHES@TERA.COM',1)
INSERT INTO seller VALUES('MARCELO WITEMBERG','M','MWITEMBERG@TERA.COM',1)
INSERT INTO seller VALUES('LILIAN SALINAS','F','LSALINAS@TERA.COM',NULL)
INSERT INTO seller VALUES('RAFAELA LIMA','F','RLIMA@TERA.COM',9)
INSERT INTO seller VALUES('CELIA TAVARES','F','CTAVARES@TERA.COM',9)
INSERT INTO seller VALUES('HERMES MACEDO','M','HMACEDO@TERA.COM',9)
INSERT INTO seller VALUES('SILVIO BAHIANA','M','SBAHIANA@TERA.COM',9)
INSERT INTO seller VALUES('DEBORA ALMEIDA','F','DALMEIDA@TERA.COM',9)
INSERT INTO seller VALUES('DAVID BORGES','M','DBORGES@TERA.COM',NULL)
INSERT INTO seller VALUES('TERESA CRISTINA','F','TCRISTINA@TERA.COM',15)
INSERT INTO seller VALUES('RODRIGO MARQUES','M','EMACHADO@TERA.COM',16)
INSERT INTO seller VALUES('CARLOS SENRA','M','CSENRA@TERA.COM',16)
INSERT INTO seller VALUES('FABIO AUGUSTO','M','FAUGUSTO@TERA.COM',16)
INSERT INTO seller VALUES('WALLACE MOREIRA','M','WMOREIRA@TERA.COM',16)
INSERT INTO seller VALUES('RENE CHIARI','M','RCHIARI@TERA.COM',16)
INSERT INTO seller VALUES('ANTONIO JESUS','M','AJESUS@TERA.COM',16)
INSERT INTO seller VALUES('PEDRO NUNES','M','PNUNES@TERA.COM',16)
GO

SELECT * FROM seller