INSERT INTO address VALUES('Quadra Quadra 303 Conjunto 05 892','São Sebastião','DF','CENTRO-OESTE', 903)
INSERT INTO address VALUES('Rua Firmino Almeida Tavares 1950','Londrina','PR','SUL', 436)
INSERT INTO address VALUES('Rua José Ismério da Silva 633','Ferraz de Vasconcelos','SP','SUDESTE', 247)
INSERT INTO address VALUES('Avenida do Contorno 124','Barbacena','MG','SUDESTE', 45)
INSERT INTO address VALUES('Rua dos Ipês 837','Foz do Iguaçu','PR','SUL', 278)
INSERT INTO address VALUES('Rua Mário Paulo Ferreira 1274','São José dos Campos','SP','SUDESTE', 801)
INSERT INTO address VALUES('Avenida Afonso Pena 1887','Goiânia','GO','CENTRO-OESTE', 296)
INSERT INTO address VALUES('Rua Pedro Sfredo 1875','Barbacena','MG','SUDESTE', 46)
INSERT INTO address VALUES('Quadra QC 16 Conjunto B Bloco 03 1981','Valparaíso de Goiás','GO','CENTRO-OESTE', 975)
INSERT INTO address VALUES('Rua Ricieri Ricardo Ticianelli 391','Londrina','PR','SUL', 437)
INSERT INTO address VALUES('Alameda José Castanheira 1656','Belém','PA','NORTE', 57)
INSERT INTO address VALUES('Rua Dezenove 1848','Rio de Janeiro','RJ','SUDESTE', 670)
INSERT INTO address VALUES('Rua Eduardo Novak 1558','Ponta Grossa','PR','SUL', 594)
INSERT INTO address VALUES('Alameda Um 945','Belém','PA','NORTE', 58)
INSERT INTO address VALUES('Rua João Alfredo 166','Duque de Caxias','RJ','SUDESTE', 235)
INSERT INTO address VALUES('Rua Zeferino Sales 1915','Recife','PE','NORDESTE', 631)
INSERT INTO address VALUES('Rua Catende 1040','Santo André','SP','SUDESTE', 757)
INSERT INTO address VALUES('Travessa Joana Tcherezov 1143','São José dos Pinhais','PR','SUL', 806)
INSERT INTO address VALUES('Rua Gabriel Monteiro de Castro 1699','Salvador','BA','NORDESTE', 718)
INSERT INTO address VALUES('Quadra QR 504 Conjunto 07 871','Samambaia','DF','CENTRO-OESTE', 742)
INSERT INTO address VALUES('Rua Pelegrino Leonetti 606','Sorocaba','SP','SUDESTE', 918)
INSERT INTO address VALUES('Rua Papa João XXIII 1957','Suzano','SP','SUDESTE', 928)
INSERT INTO address VALUES('Rua Vinícius de Morais 1867','Itabira','MG','SUDESTE', 355)
INSERT INTO address VALUES('Praça Henrique Dias 228','Olinda','PE','NORDESTE', 526)
INSERT INTO address VALUES('Rua Kalore 793','Mogi-Guaçu','SP','SUDESTE', 493)
INSERT INTO address VALUES('Rua Eugênio Paulucci 1361','Bauru','SP','SUDESTE', 51)
INSERT INTO address VALUES('Rua Tucumã 912','Campinas','SP','SUDESTE', 124)
INSERT INTO address VALUES('Caminho G 1725','Salvador','BA','NORDESTE', 719)
INSERT INTO address VALUES('Rua Quatro 17','Caraguatatuba','SP','SUDESTE', 146)
INSERT INTO address VALUES('Rua Frequência 1999','Olinda','PE','NORDESTE', 527)
INSERT INTO address VALUES('Rua Maragogipe 1862','Recife','PE','NORDESTE', 632)
INSERT INTO address VALUES('Rua Cecildes Moreira de Faria 1468','Belo Horizonte','MG','SUDESTE', 69)
INSERT INTO address VALUES('Rua Cento e Cinco 703','Sete Lagoas','MG','SUDESTE', 913)
INSERT INTO address VALUES('Rua Barão do Rio Branco 739','Sarandi','PR','SUL', 906)
INSERT INTO address VALUES('Rua Passa Quatro 1817','Uberaba','MG','SUDESTE', 953)
INSERT INTO address VALUES('Travessa Roberto Couto 615','Cariacica','ES','SUDESTE', 152)
INSERT INTO address VALUES('Rua Soldado Abílio dos Santos 1243','Vitória','ES','SUDESTE', 986)
INSERT INTO address VALUES('Rua José Vicente Bonilha 1579','Franco da Rocha','SP','SUDESTE', 290)
INSERT INTO address VALUES('Rua Nair de Souza Silva 1840','Cachoeiro de Itapemirim','ES','SUDESTE', 115)
INSERT INTO address VALUES('Rua Holanda 1796','Teresina','PI','NORDESTE', 945)
INSERT INTO address VALUES('Vila do Chá 80','Salvador','BA','NORDESTE', 720)
INSERT INTO address VALUES('Estrada Municipal dos Porretes 1842','Francisco Morato','SP','SUDESTE', 289)
INSERT INTO address VALUES('Rua Vicente Correia Lyra 844','Boa Vista','RR','NORTE', 101)
INSERT INTO address VALUES('Rua Colina Imperial 543','Petrolina','PE','NORDESTE', 567)
INSERT INTO address VALUES('Avenida M 1238','São Luís','MA','NORDESTE', 817)
INSERT INTO address VALUES('Rua Paraná 944','Americana','SP','SUDESTE', 8)
INSERT INTO address VALUES('Rua Augusto Gabriel de Paiva 1150','Santa Luzia','MG','SUDESTE', 750)
INSERT INTO address VALUES('Praça Arquiteto Neddermeyer 1456','Goiânia','GO','CENTRO-OESTE', 297)
INSERT INTO address VALUES('Rua Salvador Albano 1649','São Paulo','SP','SUDESTE', 829)
INSERT INTO address VALUES('Rua Luiz Rezzini 901','Sarandi','PR','SUL', 907)
INSERT INTO address VALUES('Rua General Valgas Neves 121','Joinville','SC','SUL', 415)
INSERT INTO address VALUES('Rua Potiragua 887','Feira de Santana','BA','NORDESTE', 243)
INSERT INTO address VALUES('Rua Plínio Câmara 1825','Fortaleza','CE','NORDESTE', 256)
INSERT INTO address VALUES('Rua Metalúrgica 809','Salvador','BA','NORDESTE', 721)
INSERT INTO address VALUES('Rua Fortaleza 493','Cuiabá','MT','CENTRO-OESTE', 205)
INSERT INTO address VALUES('Rua Tietê 1016','Recife','PE','NORDESTE', 633)
INSERT INTO address VALUES('Rua Tupi 517','Barueri','SP','SUDESTE', 50)
INSERT INTO address VALUES('Rua José Eugênio 95','Niterói','RJ','SUDESTE', 511)
INSERT INTO address VALUES('Rua Paul Scheuber 1064','Avaré','SP','SUDESTE', 41)
INSERT INTO address VALUES('Rua 1 1579','Manaus','AM','NORTE', 463)
INSERT INTO address VALUES('Rua Pirapó 803','Maringá','PR','SUL', 483)
INSERT INTO address VALUES('Rua dos Cavaquinhos 1353','Belo Horizonte','MG','SUDESTE', 70)
INSERT INTO address VALUES('Vila Alvorada 92','Rio de Janeiro','RJ','SUDESTE', 671)
INSERT INTO address VALUES('Rua Coronel Joaquim Lacerda 368','Curitiba','PR','SUL', 213)
INSERT INTO address VALUES('Rua Sergipe 113','Petrópolis','RJ','SUDESTE', 576)
INSERT INTO address VALUES('Rua Dunquerque 756','Santo André','SP','SUDESTE', 758)
INSERT INTO address VALUES('Rua Calíope 786','Goiânia','GO','CENTRO-OESTE', 298)
INSERT INTO address VALUES('Rua Professor Henrique Hargreaves 1540','Juiz de Fora','MG','SUDESTE', 421)
INSERT INTO address VALUES('Rua Arsênio Tavolieri 1262','São Paulo','SP','SUDESTE', 830)
INSERT INTO address VALUES('Avenida I 464','Maracanaú','CE','NORDESTE', 477)
INSERT INTO address VALUES('Rua Pupo Nogueira 1734','São Paulo','SP','SUDESTE', 831)
INSERT INTO address VALUES('Rua Virgílio Arcie 1798','Colombo','PR','SUL', 179)
INSERT INTO address VALUES('Rua Sátiro Dias 1275','Manaus','AM','NORTE', 464)
INSERT INTO address VALUES('Rua Paulo de Morais 1848','São Paulo','SP','SUDESTE', 832)
INSERT INTO address VALUES('Rua Caviúna 1764','Guarulhos','SP','SUDESTE', 335)
INSERT INTO address VALUES('Travessa Nossa Senhora da Conceição 1256','Tucuruí','PA','NORTE', 950)
INSERT INTO address VALUES('Rua Frederico Ozanam 1468','Pirassununga','SP','SUDESTE', 587)
INSERT INTO address VALUES('Rua Frei Miguelino 1376','João Pessoa','PB','NORDESTE', 410)
INSERT INTO address VALUES('Rua São Judas Thadeu 1249','Presidente Prudente','SP','SUDESTE', 618)
INSERT INTO address VALUES('Rua Maria Francisca 177','Serra Talhada','PE','NORDESTE', 910)
INSERT INTO address VALUES('Quadra 310 Norte Avenida NS 8 287','Palmas','TO','NORTE', 538)
INSERT INTO address VALUES('Rua João Rodrigues Chaves 1278','São Paulo','SP','SUDESTE', 833)
INSERT INTO address VALUES('Avenida São Roque 314','Salvador','BA','NORDESTE', 722)
INSERT INTO address VALUES('Rua Aladino Fim 802','Capão Bonito','SP','SUDESTE', 145)
INSERT INTO address VALUES('Rua Cravolândia 1081','Paulista','PE','NORDESTE', 560)
INSERT INTO address VALUES('Vila Doutor Menezes 103','Fortaleza','CE','NORDESTE', 257)
INSERT INTO address VALUES('Rua José da Costa Carvalho 1120','Petrópolis','RJ','SUDESTE', 577)
INSERT INTO address VALUES('Rua Adauto Pereira 915','Paulo Afonso','BA','NORDESTE', 564)
INSERT INTO address VALUES('Rua Professor Pantoja Leite 921','Rio de Janeiro','RJ','SUDESTE', 672)
INSERT INTO address VALUES('Rua Lagoa Real 1560','Rio de Janeiro','RJ','SUDESTE', 673)
INSERT INTO address VALUES('Rua Constantino de Souza 379','São Paulo','SP','SUDESTE', 834)
INSERT INTO address VALUES('Rua Saint Martin 1060','Bauru','SP','SUDESTE', 52)
INSERT INTO address VALUES('Rua Antero Moreira Campos 330','Barbacena','MG','SUDESTE', 47)
INSERT INTO address VALUES('Travessa dos Pinheiros 1160','Petrolina','PE','NORDESTE', 568)
INSERT INTO address VALUES('Alameda das Cabiúnas 904','Cataguases','MG','SUDESTE', 161)
INSERT INTO address VALUES('Rua Altino Almeida 34','Marília','SP','SUDESTE', 480)
INSERT INTO address VALUES('Praça Paulo da Portela 956','Rio de Janeiro','RJ','SUDESTE', 674)
INSERT INTO address VALUES('Rua Indalécio Arruda Costa 1542','Santos','SP','SUDESTE', 769)
INSERT INTO address VALUES('Avenida Três 1515','Paulista','PE','NORDESTE', 561)
INSERT INTO address VALUES('Rua Dezesseis 645','São Luís','MA','NORDESTE', 818)
INSERT INTO address VALUES('Rua Dom Manuel 706','São João de Meriti','RJ','SUDESTE', 789)
INSERT INTO address VALUES('Rua Lauro Muller 730','Nova Iguaçu','RJ','SUDESTE', 516)
INSERT INTO address VALUES('Rua Márcia V. 131','Redenção','PA','NORTE', 652)
INSERT INTO address VALUES('Rua Sebastião Piassa 147','Apucarana','PR','SUL', 20)
INSERT INTO address VALUES('Rodovia BR-116 1541','Curitiba','PR','SUL', 214)
INSERT INTO address VALUES('Rua 5 987','Goiânia','GO','CENTRO-OESTE', 299)
INSERT INTO address VALUES('Rua Júpiter 557','Sorocaba','SP','SUDESTE', 919)
INSERT INTO address VALUES('Rua Roma 881','Uberlândia','MG','SUDESTE', 959)
INSERT INTO address VALUES('Rua do Expedicionário 1199','Cascavel','PR','SUL', 158)
INSERT INTO address VALUES('Rua Raimundo de Carvalho 1560','Três Rios','RJ','SUDESTE', 949)
INSERT INTO address VALUES('Rua Benedita de Souza Pupo 1307','Itatiba','SP','SUDESTE', 376)
INSERT INTO address VALUES('Rua Domingos Louverturi 1900','Sete Lagoas','MG','SUDESTE', 914)
INSERT INTO address VALUES('Acesso E-Quatro 133','Porto Alegre','RS','SUL', 601)
INSERT INTO address VALUES('Rua Paulo Araújo Novaes 1308','São Paulo','SP','SUDESTE', 835)
INSERT INTO address VALUES('Rua Rio Claro 1896','São Luís','MA','NORDESTE', 819)
INSERT INTO address VALUES('Rua Arroio do Tigre 1562','Viamão','RS','SUL', 979)
INSERT INTO address VALUES('Rua 17 1617','Rio Claro','SP','SUDESTE', 668)
INSERT INTO address VALUES('Rua Oiti 1236','Araguari','MG','SUDESTE', 29)
INSERT INTO address VALUES('Rua Juruá 1589','São João de Meriti','RJ','SUDESTE', 790)
INSERT INTO address VALUES('Rua Trinta e Quatro 671','Belo Horizonte','MG','SUDESTE', 71)
INSERT INTO address VALUES('Rua Nossa Senhora da Conceição 974','Corumbá','MS','CENTRO-OESTE', 188)
INSERT INTO address VALUES('Rua Quinhentos e Quarenta e Três 1471','Volta Redonda','RJ','SUDESTE', 996)
INSERT INTO address VALUES('Quadra SHCES Quadra 0405 Bloco B 798','Cruzeiro','DF','CENTRO-OESTE', 199)
INSERT INTO address VALUES('Rua Chuí 161','Itaquaquecetuba','SP','SUDESTE', 374)
INSERT INTO address VALUES('Rua das Andorinhas 791','Jacareí','SP','SUDESTE', 398)
INSERT INTO address VALUES('Rua das Araras 1919','Salto','SP','SUDESTE', 715)
INSERT INTO address VALUES('Rua Estrela Dalva 356','Petrolina','PE','NORDESTE', 569)
INSERT INTO address VALUES('Rua Panhames 963','São Paulo','SP','SUDESTE', 836)
INSERT INTO address VALUES('Rua Domingos Jalmeno Costa 425','São José','SC','SUL', 795)
INSERT INTO address VALUES('Rua Cinco 1984','Bragança Paulista','SP','SUDESTE', 103)
INSERT INTO address VALUES('Rua Santo Agostinho 267','Gravatá','PE','NORDESTE', 324)
INSERT INTO address VALUES('Avenida Ângelo Pertini 1583','Itapira','SP','SUDESTE', 373)
INSERT INTO address VALUES('Rua Câmara 1585','Serra','ES','SUDESTE', 908)
INSERT INTO address VALUES('Rua São José 1916','Salto','SP','SUDESTE', 716)
INSERT INTO address VALUES('Rua Osório dos Santos Carvalho 1472','Umuarama','PR','SUL', 965)
INSERT INTO address VALUES('Rua Álvaro Ribeiro 214','Americana','SP','SUDESTE', 9)
INSERT INTO address VALUES('Rua Waldemiro José Borges 1284','Curitiba','PR','SUL', 215)
INSERT INTO address VALUES('Rua Padre Albino Sella 1112','Uberaba','MG','SUDESTE', 954)
INSERT INTO address VALUES('Rua Gustavo dos Santos Silveira 1305','Tatuí','SP','SUDESTE', 937)
INSERT INTO address VALUES('Rua Sarapui 719','Rio de Janeiro','RJ','SUDESTE', 675)
INSERT INTO address VALUES('Rua 77 1344','Luziânia','GO','CENTRO-OESTE', 447)
INSERT INTO address VALUES('Rua Hugo Zanini 355','Sertãozinho','SP','SUDESTE', 911)
INSERT INTO address VALUES('Estrada Itaóca 1451','São Gonçalo','RJ','SUDESTE', 778)
INSERT INTO address VALUES('Rua Picapau 1588','Feira de Santana','BA','NORDESTE', 244)
INSERT INTO address VALUES('Rua 3 1081','Araguaína','TO','NORTE', 27)
INSERT INTO address VALUES('Rua da Rabeca 456','Natal','RN','NORDESTE', 505)
INSERT INTO address VALUES('Rua Olindo Dartora 1825','Franco da Rocha','SP','SUDESTE', 291)
INSERT INTO address VALUES('2ª Travessa da Luz 1822','Jaboatão dos Guararapes','PE','NORDESTE', 387)
INSERT INTO address VALUES('Rua Maria Acciutti Bertaioli 1443','Mogi das Cruzes','SP','SUDESTE', 490)
INSERT INTO address VALUES('Rua Antônio Molina Martins Filho 253','Londrina','PR','SUL', 438)
INSERT INTO address VALUES('Avenida Dona Julieta 1802','Paranaguá','PR','SUL', 547)
INSERT INTO address VALUES('Quadra Quadra 108 Conjunto 02 1073','Recanto das Emas','DF','CENTRO-OESTE', 627)
INSERT INTO address VALUES('Avenida D 1241','Fortaleza','CE','NORDESTE', 258)
INSERT INTO address VALUES('Rua Rio Comprido 1315','Contagem','MG','SUDESTE', 181)
INSERT INTO address VALUES('Rua Moacir Albuquerque 1051','Recife','PE','NORDESTE', 634)
INSERT INTO address VALUES('Rua Marçal Soveral 1648','Passo Fundo','RS','SUL', 551)
INSERT INTO address VALUES('Rua Haroldo Veloso 1940','Ananindeua','PA','NORTE', 12)
INSERT INTO address VALUES('Avenida Eugen Wissmann 1170','Itu','SP','SUDESTE', 381)
INSERT INTO address VALUES('Rua Antônio Blanco 915','São Carlos','SP','SUDESTE', 776)
INSERT INTO address VALUES('Rua Arnaldo Carvalho Martins 70','Ituiutaba','MG','SUDESTE', 384)
INSERT INTO address VALUES('Rua Antônio Cintra Júnior 1554','Bauru','SP','SUDESTE', 53)
INSERT INTO address VALUES('Avenida Alírio Sales 728','Vitória da Conquista','BA','NORDESTE', 991)
INSERT INTO address VALUES('Rua Rio Turiaçu 1635','Recife','PE','NORDESTE', 635)
INSERT INTO address VALUES('Rua 12 1727','Rio Verde','GO','CENTRO-OESTE', 709)
INSERT INTO address VALUES('Rua Ari Barroso 1194','Jaboatão dos Guararapes','PE','NORDESTE', 388)
INSERT INTO address VALUES('Avenida Vinte e Dois de Julho 287','Macapá','AP','NORTE', 456)
INSERT INTO address VALUES('Rua Alzira de Almeida Silva 1893','Maceió','AL','NORDESTE', 460)
INSERT INTO address VALUES('Rua Tabimanu 1247','Jaboatão dos Guararapes','PE','NORDESTE', 389)
INSERT INTO address VALUES('Rua Zuca Accioly 1161','Fortaleza','CE','NORDESTE', 259)
INSERT INTO address VALUES('Rua Quinze de Agosto 968','Belém','PA','NORTE', 59)
INSERT INTO address VALUES('Rua Doutor Nivaldo Ênio de Moura e Costa 477','São José dos Pinhais','PR','SUL', 807)
INSERT INTO address VALUES('Rua Pedro Inácio Costa 1842','Porto Velho','RO','NORTE', 612)
INSERT INTO address VALUES('Rua Itaituba 1041','Jaboatão dos Guararapes','PE','NORDESTE', 390)
INSERT INTO address VALUES('Rua Mário Tamashiro 1390','Praia Grande','SP','SUDESTE', 614)
INSERT INTO address VALUES('Rua José Guimarães 1268','São Paulo','SP','SUDESTE', 837)
INSERT INTO address VALUES('Rua Doutor Moisés Santiago 1750','Juiz de Fora','MG','SUDESTE', 422)
INSERT INTO address VALUES('Rua Beni 681','Nova Iguaçu','RJ','SUDESTE', 517)
INSERT INTO address VALUES('Rua Ada Gomes da Silva 1636','São José do Rio Preto','SP','SUDESTE', 798)
INSERT INTO address VALUES('Travessa Desembargador Ivanhoe Nóbrega de Salles 1201','São Paulo','SP','SUDESTE', 838)
INSERT INTO address VALUES('Rua Hugolino Pereira dos Santos 1590','São Gonçalo','RJ','SUDESTE', 779)
INSERT INTO address VALUES('Rua Botuverá 1504','Recife','PE','NORDESTE', 636)
INSERT INTO address VALUES('Rua Antonino Araújo 1416','Arcoverde','PE','NORDESTE', 38)
INSERT INTO address VALUES('Rua Maurício Lacerda 1107','Passo Fundo','RS','SUL', 552)
INSERT INTO address VALUES('Vila Lopes 348','Fortaleza','CE','NORDESTE', 260)
INSERT INTO address VALUES('Quadra CNM 01 Bloco B 695','Ceilândia','DF','CENTRO-OESTE', 169)
INSERT INTO address VALUES('Rua Figueira 852','Nova Iguaçu','RJ','SUDESTE', 518)
INSERT INTO address VALUES('Rua Marechal Deodoro 677','São Bernardo do Campo','SP','SUDESTE', 771)
INSERT INTO address VALUES('Rua General Câmara 612','Caxias do Sul','RS','SUL', 167)
INSERT INTO address VALUES('Rua Dezesseis 634','Jaboatão dos Guararapes','PE','NORDESTE', 391)
INSERT INTO address VALUES('Rua 7 1079','Fortaleza','CE','NORDESTE', 261)
INSERT INTO address VALUES('Rua Antônio Name Chaib 1211','Campinas','SP','SUDESTE', 125)
INSERT INTO address VALUES('Rua Aristones Trindade 1470','Recife','PE','NORDESTE', 637)
INSERT INTO address VALUES('Rua Professor Sabino Silva 1041','Salvador','BA','NORDESTE', 723)
INSERT INTO address VALUES('Rua Correntes 111','São Lourenço da Mata','PE','NORDESTE', 815)
INSERT INTO address VALUES('Rua Evaldo Braga 1339','Joinville','SC','SUL', 416)
INSERT INTO address VALUES('Rua Hildemar Maia 1620','Macapá','AP','NORTE', 457)
INSERT INTO address VALUES('Rua São João Del Rei 36','Santo André','SP','SUDESTE', 759)
INSERT INTO address VALUES('Rua Francisco Fernandes Matheus 443','Franca','SP','SUDESTE', 282)
INSERT INTO address VALUES('Rua Souto Maior 1589','Campo Grande','MS','CENTRO-OESTE', 132)
INSERT INTO address VALUES('Rua Trinta e Sete 1157','Rondonópolis','MT','CENTRO-OESTE', 711)
INSERT INTO address VALUES('Rua Hum 1707','São José dos Campos','SP','SUDESTE', 802)
INSERT INTO address VALUES('Rua Escriva Beato Monsenhor 1155','Campinas','SP','SUDESTE', 126)
INSERT INTO address VALUES('Rua Seis de Janeiro 792','Montes Claros','MG','SUDESTE', 497)
INSERT INTO address VALUES('Travessa Terceira 583','Belém','PA','NORTE', 60)
INSERT INTO address VALUES('Rua Palmital 779','Montes Claros','MG','SUDESTE', 498)
INSERT INTO address VALUES('Rua Joaquim Cleto 711','São Gonçalo','RJ','SUDESTE', 780)
INSERT INTO address VALUES('Avenida Lauro Sodré 1966','Rio de Janeiro','RJ','SUDESTE', 676)
INSERT INTO address VALUES('Rua Cláudio Ciacco 617','São João da Boa Vista','SP','SUDESTE', 788)
INSERT INTO address VALUES('Quadra QE 11 Área Especial G 408','Guará','DF','CENTRO-OESTE', 329)
INSERT INTO address VALUES('Rua Trinta e Cinco 484','Belo Horizonte','MG','SUDESTE', 72)
INSERT INTO address VALUES('Rua Tupanciretã 325','Passo Fundo','RS','SUL', 553)
INSERT INTO address VALUES('Rua Belo Horizonte 132','Umuarama','PR','SUL', 966)
INSERT INTO address VALUES('Travessa Olívia Faria Barbeiro 6','São Gonçalo','RJ','SUDESTE', 781)
INSERT INTO address VALUES('Acesso Nelson Silva 1402','Porto Alegre','RS','SUL', 602)
INSERT INTO address VALUES('Rua G 526','Belo Horizonte','MG','SUDESTE', 73)
INSERT INTO address VALUES('Área Área Especial 01/04 48','Cruzeiro','DF','CENTRO-OESTE', 200)
INSERT INTO address VALUES('Rua São Luiz 683','Cariacica','ES','SUDESTE', 153)
INSERT INTO address VALUES('Alameda das Casuarinas 421','Amparo','SP','SUDESTE', 10)
INSERT INTO address VALUES('Rua Geraldo Parreiras 978','Contagem','MG','SUDESTE', 182)
INSERT INTO address VALUES('Quadra Quadra 602 Conjunto 05-C 1621','Recanto das Emas','DF','CENTRO-OESTE', 628)
INSERT INTO address VALUES('Rua X 1288','Volta Redonda','RJ','SUDESTE', 997)
INSERT INTO address VALUES('Rua da Saudade 595','Divinópolis','MG','SUDESTE', 230)
INSERT INTO address VALUES('Rua Marechal Hermes da Fonseca 121','Caraguatatuba','SP','SUDESTE', 147)
INSERT INTO address VALUES('Rua Santa Cruz 460','Itapevi','SP','SUDESTE', 371)
INSERT INTO address VALUES('Avenida Marginal A 671','Presidente Prudente','SP','SUDESTE', 619)
INSERT INTO address VALUES('Rua Maria Geralda Paulo 1108','Blumenau','SC','SUL', 95)
INSERT INTO address VALUES('Rua Odete Pires Nery 3','Vila Velha','ES','SUDESTE', 983)
INSERT INTO address VALUES('Travessa Dercy Batista 251','São Luís','MA','NORDESTE', 820)
INSERT INTO address VALUES('Rua Guilhermina Carmen Serra 1118','Curitiba','PR','SUL', 216)
INSERT INTO address VALUES('Quadra QNJ 28 355','Taguatinga','DF','CENTRO-OESTE', 935)
INSERT INTO address VALUES('Rua Professor Stroele 965','Petrópolis','RJ','SUDESTE', 578)
INSERT INTO address VALUES('Rua Tareira 259','São Paulo','SP','SUDESTE', 839)
INSERT INTO address VALUES('Rua Camille Chamoun 70','Campo Grande','MS','CENTRO-OESTE', 133)
INSERT INTO address VALUES('Rua Vitória 1648','Aparecida de Goiânia','GO','CENTRO-OESTE', 17)
INSERT INTO address VALUES('Rua Conceição 969','Japeri','RJ','SUDESTE', 402)
INSERT INTO address VALUES('Rua Chile 1577','Salvador','BA','NORDESTE', 724)
INSERT INTO address VALUES('Rua Joaquim Camargo Barros 1476','Tatuí','SP','SUDESTE', 938)
INSERT INTO address VALUES('Travessa Reino dos Andras 1581','São Paulo','SP','SUDESTE', 840)
INSERT INTO address VALUES('Rua Osório Alves 1621','Itapeva','SP','SUDESTE', 370)
INSERT INTO address VALUES('Avenida Califórnia 44','Gravataí','RS','SUL', 325)
INSERT INTO address VALUES('Rua Doutor Celestino 1312','Cruzeiro','SP','SUDESTE', 201)
INSERT INTO address VALUES('Rua Padre Aloísio Baumeister 863','Toledo','PR','SUL', 948)
INSERT INTO address VALUES('Beco Jacinto 712','Manaus','AM','NORTE', 465)
INSERT INTO address VALUES('Rua Herculano Gomes 269','Bagé','RS','SUL', 43)
INSERT INTO address VALUES('Rua José de Almeida 1896','São Paulo','SP','SUDESTE', 841)
INSERT INTO address VALUES('Rua Serra do Tubarão 1780','Londrina','PR','SUL', 439)
INSERT INTO address VALUES('Travessa Ribeiro Macedo 125','São Paulo','SP','SUDESTE', 842)
INSERT INTO address VALUES('Rua Ianomani 1597','Diadema','SP','SUDESTE', 228)
INSERT INTO address VALUES('Quadra Quadra 066 827','Luziânia','GO','CENTRO-OESTE', 448)
INSERT INTO address VALUES('Rua José Tavares Figueiredo 1420','Campos dos Goytacazes','RJ','SUDESTE', 143)
INSERT INTO address VALUES('Rua Nestor Ramos 947','Ji-Paraná','RO','NORTE', 408)
INSERT INTO address VALUES('Rua São Francisco de Salles 222','Piracicaba','SP','SUDESTE', 583)
INSERT INTO address VALUES('Rua Artur Alves de Senna 1868','Osasco','SP','SUDESTE', 532)
INSERT INTO address VALUES('Rua 24 794','Formosa','GO','CENTRO-OESTE', 255)
INSERT INTO address VALUES('Rua Setenta e Nove 1808','São Luís','MA','NORDESTE', 821)
INSERT INTO address VALUES('Rua Angelina M. Senegaglia 99','São José dos Pinhais','PR','SUL', 808)
INSERT INTO address VALUES('Rua F 456','Ponte Nova','MG','SUDESTE', 598)
INSERT INTO address VALUES('Rua Amarante 1153','Guarulhos','SP','SUDESTE', 336)
INSERT INTO address VALUES('Quadra QNN 19 Conjunto L 1196','Ceilândia','DF','CENTRO-OESTE', 170)
INSERT INTO address VALUES('Rua Quinze 1587','Araguari','MG','SUDESTE', 30)
INSERT INTO address VALUES('Rua Sulinas 924','Foz do Iguaçu','PR','SUL', 279)
INSERT INTO address VALUES('Rua Pavão 1153','Rio Verde','GO','CENTRO-OESTE', 710)
INSERT INTO address VALUES('Rua Candeias 235','Belo Horizonte','MG','SUDESTE', 74)
INSERT INTO address VALUES('Rua José Carlos Calheiros 939','Maceió','AL','NORDESTE', 461)
INSERT INTO address VALUES('Rua Morubixaba 773','São Paulo','SP','SUDESTE', 843)
INSERT INTO address VALUES('Rua Alice Nascimento Sbrissia 1637','São José dos Pinhais','PR','SUL', 809)
INSERT INTO address VALUES('Quadra Quadra 003 Conjunto A 508','Brazlândia','DF','CENTRO-OESTE', 111)
INSERT INTO address VALUES('Rua Frei Antônio 1944','Itabuna','BA','NORDESTE', 360)
INSERT INTO address VALUES('Rua Catequista Maria Marcina Almeida 1867','João Pessoa','PB','NORDESTE', 411)
INSERT INTO address VALUES('Rua Irã 749','Igarassu','PE','NORDESTE', 348)
INSERT INTO address VALUES('Rua Mário Zapelini 136','Criciúma','SC','SUL', 194)
INSERT INTO address VALUES('Passagem Brigadeiro Cecche 598','Belém','PA','NORTE', 61)
INSERT INTO address VALUES('Rua Alegrete 446','Santa Cruz do Sul','RS','SUL', 749)
INSERT INTO address VALUES('Rua Rolândia 1794','Pinhais','PR','SUL', 582)
INSERT INTO address VALUES('Quadra SHIS QI 07 Conjunto 08 907','Lago Sul','DF','CENTRO-OESTE', 431)
INSERT INTO address VALUES('Rua Dezessete 271','Uberlândia','MG','SUDESTE', 960)
INSERT INTO address VALUES('Quadra 308 Sul Alameda 7 881','Palmas','TO','NORTE', 539)
INSERT INTO address VALUES('Rua Domingos Campoy Bernal 456','São José dos Campos','SP','SUDESTE', 803)
INSERT INTO address VALUES('Rua São Borja 1158','Alegrete','RS','SUL', 5)
INSERT INTO address VALUES('Rua José Alcides Rocha 370','Fortaleza','CE','NORDESTE', 262)
INSERT INTO address VALUES('Rua Quixada 516','Santo André','SP','SUDESTE', 760)
INSERT INTO address VALUES('Vila Gouveia 1892','Fortaleza','CE','NORDESTE', 263)
INSERT INTO address VALUES('Rua Javaé 1671','Goiânia','GO','CENTRO-OESTE', 300)
INSERT INTO address VALUES('Rua Guiana Holandesa 314','Praia Grande','SP','SUDESTE', 615)
INSERT INTO address VALUES('Rua Nastácia 290','Taubaté','SP','SUDESTE', 941)
INSERT INTO address VALUES('Rua 311 1314','Catalão','GO','CENTRO-OESTE', 163)
INSERT INTO address VALUES('Rua Casemiro Paturalski 956','Ribeirão Preto','SP','SUDESTE', 660)
INSERT INTO address VALUES('Rua Professora Ilma Anechinni Zumack 592','Vitória','ES','SUDESTE', 987)
INSERT INTO address VALUES('4ª Travessa Maria das Dores da Silva 137','Camaragibe','PE','NORDESTE', 119)
INSERT INTO address VALUES('Rua do Gaia 1633','Sabará','MG','SUDESTE', 713)
INSERT INTO address VALUES('Rua G 1994','Anápolis','GO','CENTRO-OESTE', 15)
INSERT INTO address VALUES('Rua Doutor José Salvador Ferreira 467','Curitiba','PR','SUL', 217)
INSERT INTO address VALUES('Rua do Violão 444','Petrolina','PE','NORDESTE', 570)
INSERT INTO address VALUES('Beco São Paulo 1677','Santarém','PA','NORTE', 755)
INSERT INTO address VALUES('Beco Capitão Limonada 1583','Serra','ES','SUDESTE', 909)
INSERT INTO address VALUES('Rua Dezenove - A 1308','Ribeirão Preto','SP','SUDESTE', 661)
INSERT INTO address VALUES('Quadra SQN 404 Bloco B 1079','Brasília','DF','CENTRO-OESTE', 105)
INSERT INTO address VALUES('Quadra SRES Quadra 03 Bloco B 1833','Cruzeiro','DF','CENTRO-OESTE', 202)
INSERT INTO address VALUES('Rua Jorge Carlos Jardim 1093','Umuarama','PR','SUL', 967)
INSERT INTO address VALUES('Rua Jader Medeiros 912','Petrolina','PE','NORDESTE', 571)
INSERT INTO address VALUES('Rua Amparo 306','Taboão da Serra','SP','SUDESTE', 931)
INSERT INTO address VALUES('Rua Venezuela 290','Ipatinga','MG','SUDESTE', 352)
INSERT INTO address VALUES('Rua das Petúnias 1384','Sete Lagoas','MG','SUDESTE', 915)
INSERT INTO address VALUES('Rua Glenn Miller 1372','Viamão','RS','SUL', 980)
INSERT INTO address VALUES('Rua Apóstolo Matheus 830','Cachoeiro de Itapemirim','ES','SUDESTE', 116)
INSERT INTO address VALUES('Rua Nagoya 1378','Diadema','SP','SUDESTE', 229)
INSERT INTO address VALUES('Rua Domingos Peneda 616','Paranaguá','PR','SUL', 548)
INSERT INTO address VALUES('Rua Primeiro de Maio 714','Manaus','AM','NORTE', 466)
INSERT INTO address VALUES('Rua Palmares 1181','Itapecerica da Serra','SP','SUDESTE', 365)
INSERT INTO address VALUES('Rua Pedra do Indaiá 1873','Rio de Janeiro','RJ','SUDESTE', 677)
INSERT INTO address VALUES('Rua Pastor Voges 83','São Leopoldo','RS','SUL', 811)
INSERT INTO address VALUES('Rua São João 874','Tupã','SP','SUDESTE', 951)
INSERT INTO address VALUES('Rua Joviano do Nascimento 909','Ribeirão das Neves','MG','SUDESTE', 655)
INSERT INTO address VALUES('Rua Norita 379','Belo Horizonte','MG','SUDESTE', 75)
INSERT INTO address VALUES('Avenida Voizen 1364','Belo Horizonte','MG','SUDESTE', 76)
INSERT INTO address VALUES('Rua Gentil do Ouro 718','Contagem','MG','SUDESTE', 183)
INSERT INTO address VALUES('Rua Joaquim Serra 1697','São Paulo','SP','SUDESTE', 844)
INSERT INTO address VALUES('Rua Francisco Sá 1478','Teófilo Otoni','MG','SUDESTE', 944)
INSERT INTO address VALUES('Rua São Luís do Curu 1170','Fortaleza','CE','NORDESTE', 264)
INSERT INTO address VALUES('Beco do Paru 904','Salvador','BA','NORDESTE', 725)
INSERT INTO address VALUES('Avenida Doutor Hélio Campos 580','Jundiaí','SP','SUDESTE', 426)
INSERT INTO address VALUES('Rua Visconde de Nacar 251','Curitiba','PR','SUL', 218)
INSERT INTO address VALUES('Rua Hebi Ackel 1846','Guarulhos','SP','SUDESTE', 337)
INSERT INTO address VALUES('Rua D 1802','Paranavaí','PR','SUL', 549)
INSERT INTO address VALUES('Beco Três 383','Porto Alegre','RS','SUL', 603)
INSERT INTO address VALUES('Rua Pardinho 1283','Carapicuíba','SP','SUDESTE', 149)
INSERT INTO address VALUES('Rua Monte das Oliveiras 1724','São Paulo','SP','SUDESTE', 845)
INSERT INTO address VALUES('Rua Osmira Muniz 1334','Caratinga','MG','SUDESTE', 151)
INSERT INTO address VALUES('Rua Antônio Taveira de Miranda 1148','Ribeirão Preto','SP','SUDESTE', 662)
INSERT INTO address VALUES('Rua Cento e Dois 1961','Alvorada','RS','SUL', 7)
INSERT INTO address VALUES('Avenida Mantiqueira 816','Lorena','SP','SUDESTE', 445)
INSERT INTO address VALUES('Rua Engenheiro Correia Lima 1207','Goiânia','GO','CENTRO-OESTE', 301)
INSERT INTO address VALUES('Rua José Alves Nogueira 690','São Paulo','SP','SUDESTE', 846)
INSERT INTO address VALUES('Rua Eikow Kamiya 1516','Bauru','SP','SUDESTE', 54)
INSERT INTO address VALUES('Travessa Mar de Aral 1692','São Paulo','SP','SUDESTE', 847)
INSERT INTO address VALUES('Rua Almenara 527','Passos','MG','SUDESTE', 555)
INSERT INTO address VALUES('Rua Cieira 1381','Sorocaba','SP','SUDESTE', 920)
INSERT INTO address VALUES('Rua Progresso 1634','São Paulo','SP','SUDESTE', 848)
INSERT INTO address VALUES('Caminho Catu 508','Feira de Santana','BA','NORDESTE', 245)
INSERT INTO address VALUES('Rua Laurentino Xavier dos Santos 1145','São Paulo','SP','SUDESTE', 849)
INSERT INTO address VALUES('Rua João Risseto 683','Curitiba','PR','SUL', 219)
INSERT INTO address VALUES('Rua Vicente Fachinelli 1378','Londrina','PR','SUL', 440)
INSERT INTO address VALUES('Rua das Acácias 1408','Guarapuava','PR','SUL', 332)
INSERT INTO address VALUES('Rua Laranjal 427','Guarulhos','SP','SUDESTE', 338)
INSERT INTO address VALUES('Avenida Tenente Guido 746','Salvador','BA','NORDESTE', 726)
INSERT INTO address VALUES('Avenida dos Jacarandás 1855','Atibaia','SP','SUDESTE', 39)
INSERT INTO address VALUES('Rua Corumbaíba 719','Goiânia','GO','CENTRO-OESTE', 302)
INSERT INTO address VALUES('Rua Santana 777','Suzano','SP','SUDESTE', 929)
INSERT INTO address VALUES('Rua Aldemiro Francisco de Moura 1717','Mossoró','RN','NORDESTE', 501)
INSERT INTO address VALUES('Rua José Leite de Souza 1486','Itu','SP','SUDESTE', 382)
INSERT INTO address VALUES('Rua das Orquídeas 1316','Ribeirão Pires','SP','SUDESTE', 658)
INSERT INTO address VALUES('Rua São José da Coroa Grande 618','São Lourenço da Mata','PE','NORDESTE', 816)
INSERT INTO address VALUES('Rua Rio Mar 575','Paulista','PE','NORDESTE', 562)
INSERT INTO address VALUES('Rua José Marques 1405','Palmeira dos Índios','AL','NORDESTE', 545)
INSERT INTO address VALUES('Praça Coronel Tristão José de Fraga 1810','Porto Alegre','RS','SUL', 604)
INSERT INTO address VALUES('Rua P 975','Porto Alegre','RS','SUL', 605)
INSERT INTO address VALUES('Rua Vilela 1116','Imperatriz','MA','NORDESTE', 351)
INSERT INTO address VALUES('Rua Vinte e Um 60','Montes Claros','MG','SUDESTE', 499)
INSERT INTO address VALUES('Rua Coronel Caetano Júlio 426','João Pessoa','PB','NORDESTE', 412)
INSERT INTO address VALUES('Caminho 1-A 1321','Salvador','BA','NORDESTE', 727)
INSERT INTO address VALUES('Rua JI-059 434','Aparecida de Goiânia','GO','CENTRO-OESTE', 18)
INSERT INTO address VALUES('Rua Ouro Preto 1418','Sete Lagoas','MG','SUDESTE', 916)
INSERT INTO address VALUES('Vila Alegre 282','Belém','PA','NORTE', 62)
INSERT INTO address VALUES('Rua do Cadete 36','São Paulo','SP','SUDESTE', 850)
INSERT INTO address VALUES('Rua Benedito Correia 1401','Camaragibe','PE','NORDESTE', 120)
INSERT INTO address VALUES('Travessa São Carlos 1651','Jundiaí','SP','SUDESTE', 427)
INSERT INTO address VALUES('Rua Presidente Tancredo Neves 143','Araçatuba','SP','SUDESTE', 23)
INSERT INTO address VALUES('Rua Cinquenta e Três 931','Macaé','RJ','SUDESTE', 453)
INSERT INTO address VALUES('Rua Almirante Tértius Rabelo 521','Natal','RN','NORDESTE', 506)
INSERT INTO address VALUES('Rua Rio Uraria 1209','Manaus','AM','NORTE', 467)
INSERT INTO address VALUES('Rua Benfica 1767','Betim','MG','SUDESTE', 91)
INSERT INTO address VALUES('Rua Miranda Valverde 994','Rio de Janeiro','RJ','SUDESTE', 678)
INSERT INTO address VALUES('Travessa E 1399','Patos de Minas','MG','SUDESTE', 558)
INSERT INTO address VALUES('Rua Carlos Roberto Batiston 1639','Franca','SP','SUDESTE', 283)
INSERT INTO address VALUES('Rua Igaraçu 1826','Campinas','SP','SUDESTE', 127)
INSERT INTO address VALUES('Rua Flávio Beltrame 1650','Piracicaba','SP','SUDESTE', 584)
INSERT INTO address VALUES('Rua Moema 106','Jacareí','SP','SUDESTE', 399)
INSERT INTO address VALUES('Rua G 204','Canoas','RS','SUL', 144)
INSERT INTO address VALUES('Quadra 209 Sul Avenida NS 15 1164','Palmas','TO','NORTE', 540)
INSERT INTO address VALUES('Rua Pedro Fonseca 1541','Salvador','BA','NORDESTE', 728)
INSERT INTO address VALUES('Rua São Policarpo 198','Campinas','SP','SUDESTE', 128)
INSERT INTO address VALUES('Rua São Gabriel 1823','Rio de Janeiro','RJ','SUDESTE', 679)
INSERT INTO address VALUES('Rua Augusto Pinheiro 1250','Mauá','SP','SUDESTE', 486)
INSERT INTO address VALUES('5ª Travessa Sucupira do Norte 1807','Jaboatão dos Guararapes','PE','NORDESTE', 392)
INSERT INTO address VALUES('3ª Travessa Vila Nova 930','Vitória de Santo Antão','PE','NORDESTE', 994)
INSERT INTO address VALUES('Rua Efana 1755','Belford Roxo','RJ','SUDESTE', 68)
INSERT INTO address VALUES('Rua São Panfilo 1900','São Paulo','SP','SUDESTE', 851)
INSERT INTO address VALUES('Rua Rionero 517','São Paulo','SP','SUDESTE', 852)
INSERT INTO address VALUES('Rua Setenta 901','Abreu e Lima','PE','NORDESTE', 1)
INSERT INTO address VALUES('Rua Sete 396','Valinhos','SP','SUDESTE', 970)
INSERT INTO address VALUES('Rua José Basílio de Carvalho 1444','Sorocaba','SP','SUDESTE', 921)
INSERT INTO address VALUES('Rua Deoclécio Falcão Freire 1642','Mossoró','RN','NORDESTE', 502)
INSERT INTO address VALUES('Rua Itaipava 1481','Ipatinga','MG','SUDESTE', 353)
INSERT INTO address VALUES('Acesso D 692','Porto Alegre','RS','SUL', 606)
INSERT INTO address VALUES('Rua Miguel Árabe 628','Uberaba','MG','SUDESTE', 955)
INSERT INTO address VALUES('Rua Pedro de Carvalho 938','Rio de Janeiro','RJ','SUDESTE', 680)
INSERT INTO address VALUES('Rua Gaspar Valenga 27','Curitiba','PR','SUL', 220)
INSERT INTO address VALUES('Rua Felipe Betti 388','Sorocaba','SP','SUDESTE', 922)
INSERT INTO address VALUES('Rua João Ferrari 1088','Araçatuba','SP','SUDESTE', 24)
INSERT INTO address VALUES('Rua Nabor Campos 604','Contagem','MG','SUDESTE', 184)
INSERT INTO address VALUES('Rua Ternura 1849','Igarassu','PE','NORDESTE', 349)
INSERT INTO address VALUES('Rua Ferroviário Walmir Moraes 444','Recife','PE','NORDESTE', 638)
INSERT INTO address VALUES('Rua Presidente Getúlio Vargas 1902','Taubaté','SP','SUDESTE', 942)
INSERT INTO address VALUES('Rua Jamil André 1824','Mogi-Mirim','SP','SUDESTE', 495)
INSERT INTO address VALUES('Rua Itaocara 956','São Gonçalo','RJ','SUDESTE', 782)
INSERT INTO address VALUES('Rua Barão de Cotegipe 1332','Viamão','RS','SUL', 981)
INSERT INTO address VALUES('Rua Caiçara 1181','Itapecerica da Serra','SP','SUDESTE', 366)
INSERT INTO address VALUES('Rua Aristóteles Bezerra 181','Fortaleza','CE','NORDESTE', 265)
INSERT INTO address VALUES('Rua Moacir de Campos 1391','Limeira','SP','SUDESTE', 434)
INSERT INTO address VALUES('Estrada do Caputera 739','Itapecerica da Serra','SP','SUDESTE', 367)
INSERT INTO address VALUES('Rua Canela de Aracuan 1012','São Paulo','SP','SUDESTE', 853)
INSERT INTO address VALUES('Loteamento Jardim Oliveira 515','Salvador','BA','NORDESTE', 729)
INSERT INTO address VALUES('Avenida Andorinhas 1405','Ipatinga','MG','SUDESTE', 354)
INSERT INTO address VALUES('Rua Guajará 1049','Duque de Caxias','RJ','SUDESTE', 236)
INSERT INTO address VALUES('Rua Procópio Ferreira 974','Cotia','SP','SUDESTE', 190)
INSERT INTO address VALUES('Rua Entre Rios 1129','Salvador','BA','NORDESTE', 730)
INSERT INTO address VALUES('Rua México Rossi 1532','São Vicente','SP','SUDESTE', 904)
INSERT INTO address VALUES('Quadra Quadra 113 Conjunto 12 1700','Recanto das Emas','DF','CENTRO-OESTE', 629)
INSERT INTO address VALUES('Rua Berna 1473','Rio de Janeiro','RJ','SUDESTE', 681)
INSERT INTO address VALUES('Beco Figueiredo 990','Rio de Janeiro','RJ','SUDESTE', 682)
INSERT INTO address VALUES('Servidão Jatobá 353','Florianópolis','SC','SUL', 250)
INSERT INTO address VALUES('Rua da Jaqueira 1707','Itabuna','BA','NORDESTE', 361)
INSERT INTO address VALUES('Rua José Ersching 1247','Jaraguá do Sul','SC','SUL', 404)
INSERT INTO address VALUES('Rua João Locke 1581','Curitiba','PR','SUL', 221)
INSERT INTO address VALUES('Rua Antônio Taroni 1062','São Paulo','SP','SUDESTE', 854)
INSERT INTO address VALUES('Rua Dona Marita 679','Queimados','RJ','SUDESTE', 622)
INSERT INTO address VALUES('Largo do Respeito 1225','Rio de Janeiro','RJ','SUDESTE', 683)
INSERT INTO address VALUES('Rua Vera Maria de Melo Freitas 620','Mossoró','RN','NORDESTE', 503)
INSERT INTO address VALUES('Rua Armando Mendonça 806','Belém','PA','NORTE', 63)
INSERT INTO address VALUES('Quadra 1007 Sul Alameda 18 617','Palmas','TO','NORTE', 541)
INSERT INTO address VALUES('Rua Santo Onofre 1495','Belo Horizonte','MG','SUDESTE', 77)
INSERT INTO address VALUES('Rua Tupinambá 830','São Luís','MA','NORDESTE', 822)
INSERT INTO address VALUES('Travessa Dona Maria Gaiarsa 422','Santo André','SP','SUDESTE', 761)
INSERT INTO address VALUES('Rua José Roncatto 1444','Valinhos','SP','SUDESTE', 971)
INSERT INTO address VALUES('Rua Cento e Cinquenta e Um 1340','Montes Claros','MG','SUDESTE', 500)
INSERT INTO address VALUES('Rua Rio Curua 1685','São Leopoldo','RS','SUL', 812)
INSERT INTO address VALUES('Viela Moacir Alves 251','Tatuí','SP','SUDESTE', 939)
INSERT INTO address VALUES('Rua Isidoro Bispo dos Santos 368','Salvador','BA','NORDESTE', 731)
INSERT INTO address VALUES('Rua Ângelo Menel 1632','Jaraguá do Sul','SC','SUL', 405)
INSERT INTO address VALUES('Rua Tabelião João Nunes Travassos 1057','João Pessoa','PB','NORDESTE', 413)
INSERT INTO address VALUES('Avenida General San Martin 1087','Recife','PE','NORDESTE', 639)
INSERT INTO address VALUES('Quadra QR 107 216','Samambaia','DF','CENTRO-OESTE', 743)
INSERT INTO address VALUES('Rua Deputado Wanderley Júnior 1800','Curitiba','PR','SUL', 222)
INSERT INTO address VALUES('Rua Três Pontes 352','Rio de Janeiro','RJ','SUDESTE', 684)
INSERT INTO address VALUES('Rua Napoleão Francisco da Cruz Neves 1842','Paulista','PE','NORDESTE', 563)
INSERT INTO address VALUES('Rua Cinqüenta 1457','Campinas','SP','SUDESTE', 129)
INSERT INTO address VALUES('Avenida Doutor Hermínio Ometto 680','Leme','SP','SUDESTE', 433)
INSERT INTO address VALUES('Rua Xerentes 532','Goiânia','GO','CENTRO-OESTE', 303)
INSERT INTO address VALUES('Avenida Joaquim Teixeira Alves 83','Dourados','MS','CENTRO-OESTE', 233)
INSERT INTO address VALUES('Rua Ricardo Seefeldt 441','Joinville','SC','SUL', 417)
INSERT INTO address VALUES('Rua Alzira Maria Ferreira 14','Belo Horizonte','MG','SUDESTE', 78)
INSERT INTO address VALUES('Rua Pascoal Uggioni 1866','Criciúma','SC','SUL', 195)
INSERT INTO address VALUES('Rua Cachoeirinha 1','Várzea Grande','MT','CENTRO-OESTE', 976)
INSERT INTO address VALUES('Viela Evilásio Tenório Cavalcante 725','Osasco','SP','SUDESTE', 533)
INSERT INTO address VALUES('Rua Vicente Sabará Cavalcante 815','Ji-Paraná','RO','NORTE', 409)
INSERT INTO address VALUES('Rua Eudoro Lemos 1291','São Paulo','SP','SUDESTE', 855)
INSERT INTO address VALUES('Rua Frei Caneca 527','Campo Limpo Paulista','SP','SUDESTE', 141)
INSERT INTO address VALUES('Rua Erva Cidreira 843','Porto Velho','RO','NORTE', 613)
INSERT INTO address VALUES('Rua Reverendo João Euclides Pereira 255','São Paulo','SP','SUDESTE', 856)
INSERT INTO address VALUES('Rua Rio de Janeiro 1915','Santa Rita','PB','NORDESTE', 753)
INSERT INTO address VALUES('Rua Ligação 1859','Coronel Fabriciano','MG','SUDESTE', 186)
INSERT INTO address VALUES('Rua VB 6 1301','Goiânia','GO','CENTRO-OESTE', 304)
INSERT INTO address VALUES('Avenida Ricarte Soares Silva 915','Franca','SP','SUDESTE', 284)
INSERT INTO address VALUES('Quadra QR 512 Conjunto 11 1909','Samambaia','DF','CENTRO-OESTE', 744)
INSERT INTO address VALUES('Rua Projetada Avelar 127','Rio de Janeiro','RJ','SUDESTE', 685)
INSERT INTO address VALUES('Rua Recife 1130','Manaus','AM','NORTE', 468)
INSERT INTO address VALUES('Rua Manoel Antunes Pissarra 1567','Uberlândia','MG','SUDESTE', 961)
INSERT INTO address VALUES('Rua Assia Tanus Bedran 651','São João de Meriti','RJ','SUDESTE', 791)
INSERT INTO address VALUES('Rua Luís Augusto Palmerim 902','São Paulo','SP','SUDESTE', 857)
INSERT INTO address VALUES('Rua Ana Maria Horta 375','São Paulo','SP','SUDESTE', 858)
INSERT INTO address VALUES('Rua Saturno 1138','Petrolina','PE','NORDESTE', 572)
INSERT INTO address VALUES('Rua Roberto de Campos Bicudo 187','São Vicente','SP','SUDESTE', 905)
INSERT INTO address VALUES('Rua Dezoito 266','Macaé','RJ','SUDESTE', 454)
INSERT INTO address VALUES('Rua Robson Dutra de Freitas 1098','Vitória','ES','SUDESTE', 988)
INSERT INTO address VALUES('Rua Nair Alves 1811','Camaragibe','PE','NORDESTE', 121)
INSERT INTO address VALUES('Rua Ernesto Tonellatti 905','Londrina','PR','SUL', 441)
INSERT INTO address VALUES('Rua Stéfano Franceschini 837','São Paulo','SP','SUDESTE', 859)
INSERT INTO address VALUES('Rua Coronel Marinho Sobrinho 960','São Paulo','SP','SUDESTE', 860)
INSERT INTO address VALUES('Rua Agenor Leme dos Santos 957','Sorocaba','SP','SUDESTE', 923)
INSERT INTO address VALUES('Rua João Augusto Kelly 291','Barra do Piraí','RJ','SUDESTE', 48)
INSERT INTO address VALUES('Rua Dracena 1433','São Roque','SP','SUDESTE', 902)
INSERT INTO address VALUES('Beco A 279','Rio de Janeiro','RJ','SUDESTE', 686)
INSERT INTO address VALUES('Rua da Saudade 149','Cuiabá','MT','CENTRO-OESTE', 206)
INSERT INTO address VALUES('Rua Policarpo Beloni 1942','Votuporanga','SP','SUDESTE', 1000)
INSERT INTO address VALUES('Praça Montevidéo 1099','Porto Alegre','RS','SUL', 607)
INSERT INTO address VALUES('Rua Serra do Cachimbo 869','Natal','RN','NORDESTE', 507)
INSERT INTO address VALUES('Rua Tito Rosas 699','Recife','PE','NORDESTE', 640)
INSERT INTO address VALUES('Rua Dionísio Cerqueira 1487','Itajaí','SC','SUL', 363)
INSERT INTO address VALUES('Rua Professora Maria Augusta Mendonça 265','Campina Grande','PB','NORDESTE', 123)
INSERT INTO address VALUES('Rua Sônia Maria Moraes Angel Jones 778','São Paulo','SP','SUDESTE', 861)
INSERT INTO address VALUES('Avenida Três 727','São Luís','MA','NORDESTE', 823)
INSERT INTO address VALUES('Rua Descampado 1602','São Paulo','SP','SUDESTE', 862)
INSERT INTO address VALUES('Rua Vinte e Sete 1567','São José dos Campos','SP','SUDESTE', 804)
INSERT INTO address VALUES('Praça Doutor Marcelo Tostes 629','São Paulo','SP','SUDESTE', 863)
INSERT INTO address VALUES('Rua Santa Suzana 1142','Queimados','RJ','SUDESTE', 623)
INSERT INTO address VALUES('Quadra QR 414 Conjunto 09-B 1498','Samambaia','DF','CENTRO-OESTE', 745)
INSERT INTO address VALUES('Rua Júlia Skora 750','Curitiba','PR','SUL', 223)
INSERT INTO address VALUES('Rua Cunha Barbosa 822','São Paulo','SP','SUDESTE', 864)
INSERT INTO address VALUES('Quadra QR 611 Conjunto 06 82','Samambaia','DF','CENTRO-OESTE', 746)
INSERT INTO address VALUES('Rua Curuari 134','São Paulo','SP','SUDESTE', 865)
INSERT INTO address VALUES('Quadra Quadra 472 1874','Luziânia','GO','CENTRO-OESTE', 449)
INSERT INTO address VALUES('Travessa Grassi 1871','São Paulo','SP','SUDESTE', 866)
INSERT INTO address VALUES('Rua João Manoel Bittencourt 902','São José','SC','SUL', 796)
INSERT INTO address VALUES('Rua Reinaldo Uebel 294','São Leopoldo','RS','SUL', 813)
INSERT INTO address VALUES('Rua Conde Siciliano 134','São Bernardo do Campo','SP','SUDESTE', 772)
INSERT INTO address VALUES('Rua da Marcassita 928','Petrolina','PE','NORDESTE', 573)
INSERT INTO address VALUES('Rua das Camélias 1658','Castro','PR','SUL', 159)
INSERT INTO address VALUES('Rua Valeria 1784','São Gonçalo','RJ','SUDESTE', 783)
INSERT INTO address VALUES('Rua Turiassu 1020','Campo Grande','MS','CENTRO-OESTE', 134)
INSERT INTO address VALUES('Praça Henrique Mendes 1656','Maracanaú','CE','NORDESTE', 478)
INSERT INTO address VALUES('Quadra Quadra 009 Conjunto J 468','Gama','DF','CENTRO-OESTE', 293)
INSERT INTO address VALUES('Travessa dos Artilheiros 805','Osasco','SP','SUDESTE', 534)
INSERT INTO address VALUES('Rua João Previtalle 872','Valinhos','SP','SUDESTE', 972)
INSERT INTO address VALUES('Rua João Ferrarine 402','Colombo','PR','SUL', 180)
INSERT INTO address VALUES('Largo dos Caixeiros Viajantes 92','Porto Alegre','RS','SUL', 608)
INSERT INTO address VALUES('Rua Rio Araguari 1123','Macapá','AP','NORTE', 458)
INSERT INTO address VALUES('Rua Irmã Ancila 1530','Santa Luzia','MG','SUDESTE', 751)
INSERT INTO address VALUES('Rua São Pedro 1893','Manaus','AM','NORTE', 469)
INSERT INTO address VALUES('Quadra Quadra 041 449','Gama','DF','CENTRO-OESTE', 294)
INSERT INTO address VALUES('Rua Joaquim Gregório da Silva 5','Ribeirão das Neves','MG','SUDESTE', 656)
INSERT INTO address VALUES('Viela Antas 610','Guarulhos','SP','SUDESTE', 339)
INSERT INTO address VALUES('Passagem Bento Amador 1603','Belém','PA','NORTE', 64)
INSERT INTO address VALUES('Rua Sinval Soares 1096','Itaúna','MG','SUDESTE', 379)
INSERT INTO address VALUES('Quadra EQ 16/26 605','Gama','DF','CENTRO-OESTE', 295)
INSERT INTO address VALUES('Rua João Gabriel de Lima 297','Campo Limpo Paulista','SP','SUDESTE', 142)
INSERT INTO address VALUES('Rua das Palmas 1848','Fortaleza','CE','NORDESTE', 266)
INSERT INTO address VALUES('Quadra Quadra 127 263','Novo Gama','GO','CENTRO-OESTE', 525)
INSERT INTO address VALUES('Rua São João 1974','Goiânia','GO','CENTRO-OESTE', 305)
INSERT INTO address VALUES('Rua Presidente Getúlio Vargas 129','Cariacica','ES','SUDESTE', 154)
INSERT INTO address VALUES('Rua Seis 380','Coronel Fabriciano','MG','SUDESTE', 187)
INSERT INTO address VALUES('Rua Manuel Tomar 1434','São Paulo','SP','SUDESTE', 867)
INSERT INTO address VALUES('Avenida Thomaz Gonzaga 53','Salvador','BA','NORDESTE', 732)
INSERT INTO address VALUES('Vila Mariana 148','Itaúna','MG','SUDESTE', 380)
INSERT INTO address VALUES('Rua Antônio Austregesilo 486','Rio de Janeiro','RJ','SUDESTE', 687)
INSERT INTO address VALUES('Rua Doze de Fevereiro 1401','Rio de Janeiro','RJ','SUDESTE', 688)
INSERT INTO address VALUES('Rua Vinícius de Moraes 1794','Piracicaba','SP','SUDESTE', 585)
INSERT INTO address VALUES('Rua José de Oliveira Dias 1766','Taboão da Serra','SP','SUDESTE', 932)
INSERT INTO address VALUES('Rua José Dias 1223','Cataguases','MG','SUDESTE', 162)
INSERT INTO address VALUES('Rua Maria Auxiliadora Diniz Laburu 639','Campo Grande','MS','CENTRO-OESTE', 135)
INSERT INTO address VALUES('Rua Sebastião Nicolino 895','Cruzeiro','SP','SUDESTE', 203)
INSERT INTO address VALUES('Praça Diego Sanches Salim Longo Pereira 1408','Lins','SP','SUDESTE', 435)
INSERT INTO address VALUES('Travessa Santa Clara 1406','Botucatu','SP','SUDESTE', 102)
INSERT INTO address VALUES('Rua Maria Lourdes de Franca 566','Sousa','PB','NORDESTE', 925)
INSERT INTO address VALUES('Rua Belo Horizonte 663','Rio de Janeiro','RJ','SUDESTE', 689)
INSERT INTO address VALUES('Avenida Doutor Júlio Maranhão 1313','Jaboatão dos Guararapes','PE','NORDESTE', 393)
INSERT INTO address VALUES('Rua Doutor Fábio de Mello Bonilha 1383','Ponta Grossa','PR','SUL', 595)
INSERT INTO address VALUES('Rua Manaus 440','Cuiabá','MT','CENTRO-OESTE', 207)
INSERT INTO address VALUES('Rua Cafarnaum 1491','Recife','PE','NORDESTE', 641)
INSERT INTO address VALUES('Rua Almirante Lobo 359','São Paulo','SP','SUDESTE', 868)
INSERT INTO address VALUES('Travessa Darci Vargas 745','Rio de Janeiro','RJ','SUDESTE', 690)
INSERT INTO address VALUES('Rua Dezoito 1089','Resende','RJ','SUDESTE', 653)
INSERT INTO address VALUES('Estrada da Independência 1030','Rio de Janeiro','RJ','SUDESTE', 691)
INSERT INTO address VALUES('Rua Treze de Maio 1906','Amparo','SP','SUDESTE', 11)
INSERT INTO address VALUES('Rua Pará 1862','Castro','PR','SUL', 160)
INSERT INTO address VALUES('Rua Josefa Amicci 542','Avaré','SP','SUDESTE', 42)
INSERT INTO address VALUES('Vila Tatuí 1418','Fortaleza','CE','NORDESTE', 267)
INSERT INTO address VALUES('Rotatória Clóvis Ferraz 643','Ourinhos','SP','SUDESTE', 536)
INSERT INTO address VALUES('Rua São Francisco 543','Olinda','PE','NORDESTE', 528)
INSERT INTO address VALUES('Avenida João Furtado Gouveia Sobrinho 1273','Itatiba','SP','SUDESTE', 377)
INSERT INTO address VALUES('Rua Alba Valdez 310','Camaragibe','PE','NORDESTE', 122)
INSERT INTO address VALUES('Rua Nova Xavantina 237','Cuiabá','MT','CENTRO-OESTE', 208)
INSERT INTO address VALUES('Rua Passagem 1524','Governador Valadares','MG','SUDESTE', 323)
INSERT INTO address VALUES('Rua Constantino Rosa 792','São Paulo','SP','SUDESTE', 869)
INSERT INTO address VALUES('Rua Nova Friburgo 200','Cotia','SP','SUDESTE', 191)
INSERT INTO address VALUES('Rua Carlos D. Fernandes 1852','Santa Rita','PB','NORDESTE', 754)
INSERT INTO address VALUES('Rua José Lopes Berruezo 6','Presidente Prudente','SP','SUDESTE', 620)
INSERT INTO address VALUES('Avenida Principal 1656','Cuiabá','MT','CENTRO-OESTE', 209)
INSERT INTO address VALUES('Travessa do Geraldo 1797','Rio de Janeiro','RJ','SUDESTE', 692)
INSERT INTO address VALUES('1ª Travessa de Esperança Viver 1184','Salvador','BA','NORDESTE', 733)
INSERT INTO address VALUES('Rua dos Jívaros 691','Campinas','SP','SUDESTE', 130)
INSERT INTO address VALUES('Rua Tolentino Xavier Lemos 361','Vitória','ES','SUDESTE', 989)
INSERT INTO address VALUES('Rua Treze de Maio 1617','Guarujá','SP','SUDESTE', 334)
INSERT INTO address VALUES('Rua Serra dos Penitentes 51','Itapevi','SP','SUDESTE', 372)
INSERT INTO address VALUES('Rua Rosalino Silva 464','São Paulo','SP','SUDESTE', 870)
INSERT INTO address VALUES('Rua Roberto Romão de Moraes 1366','São Paulo','SP','SUDESTE', 871)
INSERT INTO address VALUES('Rua Desembargador Cícero de Toledo Piza 1838','São Paulo','SP','SUDESTE', 872)
INSERT INTO address VALUES('Rua Sorocaba 1088','Gurupi','TO','NORTE', 346)
INSERT INTO address VALUES('Beco Califórnia 1073','Belo Horizonte','MG','SUDESTE', 79)
INSERT INTO address VALUES('Rua Manoel Ferreira 339','Florianópolis','SC','SUL', 251)
INSERT INTO address VALUES('Rua Francisco Pinheiro 1336','São Gonçalo','RJ','SUDESTE', 784)
INSERT INTO address VALUES('Rua Ferdinando de Lúcia 215','São Paulo','SP','SUDESTE', 873)
INSERT INTO address VALUES('Rua Umbelino Bueno de Carvalho 1609','São Paulo','SP','SUDESTE', 874)
INSERT INTO address VALUES('Rua Laranjeira 672','Divinópolis','MG','SUDESTE', 231)
INSERT INTO address VALUES('Rua Bento Soares Mota 185','São Paulo','SP','SUDESTE', 875)
INSERT INTO address VALUES('Rua Feliciano Madruga 339','João Pessoa','PB','NORDESTE', 414)
INSERT INTO address VALUES('Travessa São Francisco 82','Cacoal','RO','NORTE', 118)
INSERT INTO address VALUES('Quadra QNN 03 Conjunto N 1864','Ceilândia','DF','CENTRO-OESTE', 171)
INSERT INTO address VALUES('1ª Travessa Santa Tereza 137','Salvador','BA','NORDESTE', 734)
INSERT INTO address VALUES('Beco José Dírcio 75','Belo Horizonte','MG','SUDESTE', 80)
INSERT INTO address VALUES('Rua Pedro Américo 1498','Goiânia','GO','CENTRO-OESTE', 306)
INSERT INTO address VALUES('Rua São Jorge 1474','Rio Branco','AC','NORTE', 667)
INSERT INTO address VALUES('Rua Buriti 1178','Queimados','RJ','SUDESTE', 624)
INSERT INTO address VALUES('Rua Alberto Lotto 1049','Araras','SP','SUDESTE', 35)
INSERT INTO address VALUES('Rua Barão de Vallim 1300','São Paulo','SP','SUDESTE', 876)
INSERT INTO address VALUES('Avenida Euclides de Figueiredo 1156','Piracicaba','SP','SUDESTE', 586)
INSERT INTO address VALUES('Travessa Vinícius Coutinho 1146','Colatina','ES','SUDESTE', 177)
INSERT INTO address VALUES('Rua Operários 1048','Paranavaí','PR','SUL', 550)
INSERT INTO address VALUES('Quadra QNN 19 Conjunto B 185','Ceilândia','DF','CENTRO-OESTE', 172)
INSERT INTO address VALUES('Avenida Nossa Senhora da Lapa 620','Cubatão','SP','SUDESTE', 204)
INSERT INTO address VALUES('Avenida dos Semaneiros 35','São Paulo','SP','SUDESTE', 877)
INSERT INTO address VALUES('Rua Osterno Potenciano e Silva 712','Goiânia','GO','CENTRO-OESTE', 307)
INSERT INTO address VALUES('3ª Travessa Trinta e Um de Março 308','Abreu e Lima','PE','NORDESTE', 2)
INSERT INTO address VALUES('Rua Tomaz Sochaczewski 1882','São José dos Pinhais','PR','SUL', 810)
INSERT INTO address VALUES('Rua do Parque 1174','São Carlos','SP','SUDESTE', 777)
INSERT INTO address VALUES('Quadra 42 101','Planaltina de Goiás','GO','CENTRO-OESTE', 589)
INSERT INTO address VALUES('Rua O 1063','Itabira','MG','SUDESTE', 356)
INSERT INTO address VALUES('Rua Caiapônia 719','Guarulhos','SP','SUDESTE', 340)
INSERT INTO address VALUES('Rua Ribeira do Pombal 988','Rio de Janeiro','RJ','SUDESTE', 693)
INSERT INTO address VALUES('Rua Jardim Itacaranha 581','Salvador','BA','NORDESTE', 735)
INSERT INTO address VALUES('Rua José Antônio Leme 585','Sorocaba','SP','SUDESTE', 924)
INSERT INTO address VALUES('Rua Terra Boa 1075','Recife','PE','NORDESTE', 642)
INSERT INTO address VALUES('Servidão Robson Fernendes da Rosa 1845','Teresópolis','RJ','SUDESTE', 947)
INSERT INTO address VALUES('Rua das Flores 660','Florianópolis','SC','SUL', 252)
INSERT INTO address VALUES('Travessa Avenida Central 197','Caxias','MA','NORDESTE', 166)
INSERT INTO address VALUES('Rua João Kubinski 516','Ponta Grossa','PR','SUL', 596)
INSERT INTO address VALUES('Rua Presidente Prudente 1106','Catanduva','SP','SUDESTE', 164)
INSERT INTO address VALUES('Rua Hipólito Vasconcelos 1195','Rio de Janeiro','RJ','SUDESTE', 694)
INSERT INTO address VALUES('Rua Conselheiro Lafayete 928','Viamão','RS','SUL', 982)
INSERT INTO address VALUES('Rua Antônio Rossi 1092','Criciúma','SC','SUL', 196)
INSERT INTO address VALUES('Rua Serra dos Carajás 306','Guarulhos','SP','SUDESTE', 341)
INSERT INTO address VALUES('Rua Elísio Vetorello 19','Francisco Beltrão','PR','SUL', 287)
INSERT INTO address VALUES('Avenida Domingos Jorge Velho 815','Manaus','AM','NORTE', 470)
INSERT INTO address VALUES('Rua Curitiba 1771','Franca','SP','SUDESTE', 285)
INSERT INTO address VALUES('Rua Palestina 1867','Arapiraca','AL','NORDESTE', 31)
INSERT INTO address VALUES('Quadra Quadra 270 1349','Luziânia','GO','CENTRO-OESTE', 450)
INSERT INTO address VALUES('Rua Manoel da Costa Ferreira 122','Feira de Santana','BA','NORDESTE', 246)
INSERT INTO address VALUES('Rua Vinte e Cinco-A 44','Volta Redonda','RJ','SUDESTE', 998)
INSERT INTO address VALUES('Rua Senhor Lais Amadi 634','Valinhos','SP','SUDESTE', 973)
INSERT INTO address VALUES('Rua Benjamin Rodrigues Pereira 946','Mogi das Cruzes','SP','SUDESTE', 491)
INSERT INTO address VALUES('Rua Joaquim Silva 1904','São Gonçalo','RJ','SUDESTE', 785)
INSERT INTO address VALUES('Praça Olívia Vaz Romero 1713','Mogi das Cruzes','SP','SUDESTE', 492)
INSERT INTO address VALUES('Quadra SQS 313 Bloco C 1395','Brasília','DF','CENTRO-OESTE', 106)
INSERT INTO address VALUES('Alameda Praia de Itacaré 1735','Salvador','BA','NORDESTE', 736)
INSERT INTO address VALUES('Rua Índia 932','Francisco Beltrão','PR','SUL', 288)
INSERT INTO address VALUES('Rua César Marengo 41','São Paulo','SP','SUDESTE', 878)
INSERT INTO address VALUES('Rua Teresópolis 1359','Santo André','SP','SUDESTE', 762)
INSERT INTO address VALUES('Rua Novo Horizonte 1700','Campo Grande','MS','CENTRO-OESTE', 136)
INSERT INTO address VALUES('Rua Gauguim 775','Cotia','SP','SUDESTE', 192)
INSERT INTO address VALUES('Rua São Geraldo 969','Duque de Caxias','RJ','SUDESTE', 237)
INSERT INTO address VALUES('Rua Cadete Edson 1899','Resende','RJ','SUDESTE', 654)
INSERT INTO address VALUES('Rua Othon Palace 1172','Embu','SP','SUDESTE', 240)
INSERT INTO address VALUES('Rua Poeta Paulo Leminski Filho 985','Maringá','PR','SUL', 484)
INSERT INTO address VALUES('Rua Engenheiro César Polilo 738','São Paulo','SP','SUDESTE', 879)
INSERT INTO address VALUES('Rua 271 1429','Goiânia','GO','CENTRO-OESTE', 308)
INSERT INTO address VALUES('Travessa Tamba 1562','Rio de Janeiro','RJ','SUDESTE', 695)
INSERT INTO address VALUES('Rua Alberto Leite 443','Rio de Janeiro','RJ','SUDESTE', 696)
INSERT INTO address VALUES('Avenida Portugal 984','Várzea Paulista','SP','SUDESTE', 978)
INSERT INTO address VALUES('Rua Arminda de Lima 1352','Guarulhos','SP','SUDESTE', 342)
INSERT INTO address VALUES('Travessa Venezuela 139','Natal','RN','NORDESTE', 508)
INSERT INTO address VALUES('Rua Luciano Marrano 711','São Paulo','SP','SUDESTE', 880)
INSERT INTO address VALUES('Rua Jorge Joaquim Carneiro 1629','Florianópolis','SC','SUL', 253)
INSERT INTO address VALUES('Rua Padre Demerval Gomes 840','Belo Horizonte','MG','SUDESTE', 81)
INSERT INTO address VALUES('Rua Doutor Geraldo de Andrade 205','Recife','PE','NORDESTE', 643)
INSERT INTO address VALUES('Rua Dom Bosco 950','Contagem','MG','SUDESTE', 185)
INSERT INTO address VALUES('Rua Comandante Marcolino de Souza 816','Petrópolis','RJ','SUDESTE', 579)
INSERT INTO address VALUES('Rua Campo Belo 425','Cariacica','ES','SUDESTE', 155)
INSERT INTO address VALUES('Rua Trinta e Cinco 236','Abreu e Lima','PE','NORDESTE', 3)
INSERT INTO address VALUES('Alameda Pinhão 291','Bauru','SP','SUDESTE', 55)
INSERT INTO address VALUES('Rua Filipense 364','Manaus','AM','NORTE', 471)
INSERT INTO address VALUES('Quadra Quadra 605 Conjunto 07 810','Recanto das Emas','DF','CENTRO-OESTE', 630)
INSERT INTO address VALUES('Quadra QI 07 Conjunto K 325','Guará','DF','CENTRO-OESTE', 330)
INSERT INTO address VALUES('Rua Professora Mazini Bueno 936','Niterói','RJ','SUDESTE', 512)
INSERT INTO address VALUES('Rua Nhanhá do Couto 1233','Goiânia','GO','CENTRO-OESTE', 309)
INSERT INTO address VALUES('Largo Paula Cândido 235','Rio de Janeiro','RJ','SUDESTE', 697)
INSERT INTO address VALUES('Passagem Emília Ribeiro 877','Ananindeua','PA','NORTE', 13)
INSERT INTO address VALUES('Rua José Provezi 1526','Blumenau','SC','SUL', 96)
INSERT INTO address VALUES('Passagem Nossa Senhora das Graças 1844','Santarém','PA','NORTE', 756)
INSERT INTO address VALUES('Rua do Viveiro 427','Recife','PE','NORDESTE', 644)
INSERT INTO address VALUES('Rua Walter Nascimento Bezerra 245','Araraquara','SP','SUDESTE', 32)
INSERT INTO address VALUES('Rua Seis 1375','Santa Luzia','MG','SUDESTE', 752)
INSERT INTO address VALUES('Rua SC 22 1930','Goiânia','GO','CENTRO-OESTE', 310)
INSERT INTO address VALUES('Rua João Quirino 1641','Planaltina','DF','CENTRO-OESTE', 588)
INSERT INTO address VALUES('Rua Sete 1123','Guarapari','ES','SUDESTE', 331)
INSERT INTO address VALUES('Rua Colônia Libanêsa 1104','Anápolis','GO','CENTRO-OESTE', 16)
INSERT INTO address VALUES('Rua Ladislau Paszkiewicz 649','Curitiba','PR','SUL', 224)
INSERT INTO address VALUES('Rua Doutor Nilo Peçanha 953','Niterói','RJ','SUDESTE', 513)
INSERT INTO address VALUES('Rua Sete de Setembro 1171','Eunápolis','BA','NORDESTE', 242)
INSERT INTO address VALUES('Rua Antônio Brunhollo 1421','Nova Friburgo','RJ','SUDESTE', 515)
INSERT INTO address VALUES('Rua Doutor Francisco Antunes Júnior 410','Pelotas','RS','SUL', 566)
INSERT INTO address VALUES('Rua Cacilda Silva 867','Taubaté','SP','SUDESTE', 943)
INSERT INTO address VALUES('Rua Caravelas 1655','Vitória da Conquista','BA','NORDESTE', 992)
INSERT INTO address VALUES('Rua José Valente dos Santos 856','Macapá','AP','NORTE', 459)
INSERT INTO address VALUES('Rua Copixaba 1370','Recife','PE','NORDESTE', 645)
INSERT INTO address VALUES('Rua Manoel Ferreira Leite 560','Palmas','TO','NORTE', 542)
INSERT INTO address VALUES('2ª Travessa Itabira 1514','Recife','PE','NORDESTE', 646)
INSERT INTO address VALUES('Avenida Eça de Queirós Lages de Mesquita 293','Itaituba','PA','NORTE', 362)
INSERT INTO address VALUES('Rua Victório Venzol 897','São Bernardo do Campo','SP','SUDESTE', 773)
INSERT INTO address VALUES('Rua Ubatuba 1732','Jaboatão dos Guararapes','PE','NORDESTE', 394)
INSERT INTO address VALUES('Rua Nazaré 260','Ribeirão Pires','SP','SUDESTE', 659)
INSERT INTO address VALUES('Quadra SHIS QL 06 Conjunto 03 1561','Lago Sul','DF','CENTRO-OESTE', 432)
INSERT INTO address VALUES('Rua Itapuã 104','Recife','PE','NORDESTE', 647)
INSERT INTO address VALUES('Estrada Barão do Rio Branco 812','Santo André','SP','SUDESTE', 763)
INSERT INTO address VALUES('Rua Santa Cláudia 814','Manaus','AM','NORTE', 472)
INSERT INTO address VALUES('Rua Clair Camargo 1387','Ribeirão Preto','SP','SUDESTE', 663)
INSERT INTO address VALUES('Rua Seis 1226','Itapetininga','SP','SUDESTE', 369)
INSERT INTO address VALUES('Rua Niterói 845','Uberlândia','MG','SUDESTE', 962)
INSERT INTO address VALUES('Rua dos Cesteiros 485','Caxias do Sul','RS','SUL', 168)
INSERT INTO address VALUES('Rua Benjamim Pereira Da Silva 1784','Hortolândia','SP','SUDESTE', 347)
INSERT INTO address VALUES('Rua Ernesto Nazaré 642','Tatuí','SP','SUDESTE', 940)
INSERT INTO address VALUES('Rua Xerentes 206','Goiânia','GO','CENTRO-OESTE', 311)
INSERT INTO address VALUES('Beco B 1801','Porto Alegre','RS','SUL', 609)
INSERT INTO address VALUES('Rua Rosa Silvestre 1787','Fortaleza','CE','NORDESTE', 268)
INSERT INTO address VALUES('Servidão Irineu João de Souza 1294','São José','SC','SUL', 797)
INSERT INTO address VALUES('Quadra EQNN 22/24 Bloco F 815','Ceilândia','DF','CENTRO-OESTE', 173)
INSERT INTO address VALUES('Rua T 654','Goiânia','GO','CENTRO-OESTE', 312)
INSERT INTO address VALUES('Rua Antônio Carlos Coutinho 1240','Belo Horizonte','MG','SUDESTE', 82)
INSERT INTO address VALUES('Rua Nossa Senhora do Amparo 1399','Belo Horizonte','MG','SUDESTE', 83)
INSERT INTO address VALUES('Rua 15 de Maio 1904','Natal','RN','NORDESTE', 509)
INSERT INTO address VALUES('Rua Miguel Calmon 79','Duque de Caxias','RJ','SUDESTE', 238)
INSERT INTO address VALUES('Rua A 371','Vitória de Santo Antão','PE','NORDESTE', 995)
INSERT INTO address VALUES('Rua Amapá 1591','Nova Iguaçu','RJ','SUDESTE', 519)
INSERT INTO address VALUES('Rua Jorge Palmiro Mercado 894','São Paulo','SP','SUDESTE', 881)
INSERT INTO address VALUES('Rua Nelson Fernandes 184','Vila Velha','ES','SUDESTE', 984)
INSERT INTO address VALUES('Rua Marechal Eurico Gaspar Dutra 1015','São José do Rio Preto','SP','SUDESTE', 799)
INSERT INTO address VALUES('Rua Manoel Rubim 81','Belo Horizonte','MG','SUDESTE', 84)
INSERT INTO address VALUES('Avenida João Roberto Correia 1887','Praia Grande','SP','SUDESTE', 616)
INSERT INTO address VALUES('Rua Jacy Lopes 1581','Ponte Nova','MG','SUDESTE', 599)
INSERT INTO address VALUES('Rua Itabuna 1213','Nova Iguaçu','RJ','SUDESTE', 520)
INSERT INTO address VALUES('Travessa João Batista 1342','São Gonçalo','RJ','SUDESTE', 786)
INSERT INTO address VALUES('Avenida Barão do Rego Barros 792','São Paulo','SP','SUDESTE', 882)
INSERT INTO address VALUES('Estrada dos Bandeirantes 451','Rio de Janeiro','RJ','SUDESTE', 698)
INSERT INTO address VALUES('Avenida Pedro Ludovico Teixeira 1504','Goiânia','GO','CENTRO-OESTE', 313)
INSERT INTO address VALUES('Praça Craveiro do Campo 253','São Paulo','SP','SUDESTE', 883)
INSERT INTO address VALUES('Rua Judéia 124','Luziânia','GO','CENTRO-OESTE', 451)
INSERT INTO address VALUES('Rua Rolando Pedreira 1636','Rio de Janeiro','RJ','SUDESTE', 699)
INSERT INTO address VALUES('Rua Paulo Mangabeira Albernaz 131','Sumaré','SP','SUDESTE', 926)
INSERT INTO address VALUES('Rua Carlos Alberto 1097','Nova Iguaçu','RJ','SUDESTE', 521)
INSERT INTO address VALUES('Travessa Itu 48','Umuarama','PR','SUL', 968)
INSERT INTO address VALUES('Travessa Pratinha 389','Uberaba','MG','SUDESTE', 956)
INSERT INTO address VALUES('Rua Victor Cornélio 960','Londrina','PR','SUL', 442)
INSERT INTO address VALUES('Rua Suely Pereira 598','Bagé','RS','SUL', 44)
INSERT INTO address VALUES('Rua Maria Fressato Basso 1281','Araucária','PR','SUL', 36)
INSERT INTO address VALUES('Rua General Osório 419','Blumenau','SC','SUL', 97)
INSERT INTO address VALUES('Rua Artur Gomes de Carvalho 1008','Salvador','BA','NORDESTE', 737)
INSERT INTO address VALUES('Avenida Doutor Flávio Rocha 644','Franca','SP','SUDESTE', 286)
INSERT INTO address VALUES('Quadra SQS 116 Bloco C 273','Brasília','DF','CENTRO-OESTE', 107)
INSERT INTO address VALUES('Rua Santinho Linhares 1589','Itabira','MG','SUDESTE', 357)
INSERT INTO address VALUES('Rua Campo Verde 795','Aparecida de Goiânia','GO','CENTRO-OESTE', 19)
INSERT INTO address VALUES('Rua Rio Paramirim 1319','Ribeirão Preto','SP','SUDESTE', 664)
INSERT INTO address VALUES('Rodovia SC 448 217','Criciúma','SC','SUL', 197)
INSERT INTO address VALUES('Rua Airton Sena 1712','São Paulo','SP','SUDESTE', 884)
INSERT INTO address VALUES('Travessa Patrícia Vieira 1335','Patos','PB','NORDESTE', 557)
INSERT INTO address VALUES('Rua Quatro 388','Petrolina','PE','NORDESTE', 574)
INSERT INTO address VALUES('Rua das Bandeiras 175','Marília','SP','SUDESTE', 481)
INSERT INTO address VALUES('Rua Quartzo 206','Rio de Janeiro','RJ','SUDESTE', 700)
INSERT INTO address VALUES('Rua São Geraldo 1935','Uberaba','MG','SUDESTE', 957)
INSERT INTO address VALUES('Rua Aracaju 1273','Belo Horizonte','MG','SUDESTE', 85)
INSERT INTO address VALUES('Rua Bonifácio Guimarães 1069','Ponte Nova','MG','SUDESTE', 600)
INSERT INTO address VALUES('Rua Maestro Alberto Frateschi 1417','Uberaba','MG','SUDESTE', 958)
INSERT INTO address VALUES('Rua Francisco Bernardo Boticher 1245','Joinville','SC','SUL', 418)
INSERT INTO address VALUES('Rua Armando Tavares 755','Santo Antônio de Jesus','BA','NORDESTE', 768)
INSERT INTO address VALUES('Rua Teotônio Vilela 586','Salvador','BA','NORDESTE', 738)
INSERT INTO address VALUES('Rua Rosa Claro Martins 1709','São José dos Campos','SP','SUDESTE', 805)
INSERT INTO address VALUES('Passagem São Pedro 522','Belém','PA','NORTE', 65)
INSERT INTO address VALUES('Rua Apólo de Almeida 1644','Jundiaí','SP','SUDESTE', 428)
INSERT INTO address VALUES('Beco Quatro de Julho 880','Manaus','AM','NORTE', 473)
INSERT INTO address VALUES('Rua Santos Dumont 13','Jataí','GO','CENTRO-OESTE', 407)
INSERT INTO address VALUES('Rua Pedro Rozio Coelho 708','Londrina','PR','SUL', 443)
INSERT INTO address VALUES('Rua Coronel Estanislau Frota 1787','Sobral','CE','NORDESTE', 917)
INSERT INTO address VALUES('Rua Carlos Rosas 991','Alagoinhas','BA','NORDESTE', 4)
INSERT INTO address VALUES('Rua Bela Vista 650','Salvador','BA','NORDESTE', 739)
INSERT INTO address VALUES('Rua João Puchaski 1595','Curitiba','PR','SUL', 225)
INSERT INTO address VALUES('Rua C 1112','Sabará','MG','SUDESTE', 714)
INSERT INTO address VALUES('Quadra Cento e Cinqüenta e Sete 618','Ananindeua','PA','NORTE', 14)
INSERT INTO address VALUES('Rua José Sampaio de Oliveira 722','Araçatuba','SP','SUDESTE', 25)
INSERT INTO address VALUES('Rua Inglaterra 228','Fortaleza','CE','NORDESTE', 269)
INSERT INTO address VALUES('Rua Luiz Fachini 225','Bebedouro','SP','SUDESTE', 56)
INSERT INTO address VALUES('Rua do Café 1252','Poços de Caldas','MG','SUDESTE', 592)
INSERT INTO address VALUES('Quadra QS 605 Bloco A 1381','Samambaia','DF','CENTRO-OESTE', 747)
INSERT INTO address VALUES('Rua Professora Julieta Nicolich da Costa 1605','Florianópolis','SC','SUL', 254)
INSERT INTO address VALUES('Rua Areado 854','Carapicuíba','SP','SUDESTE', 150)
INSERT INTO address VALUES('Rua Barão de Tefe 891','Petrópolis','RJ','SUDESTE', 580)
INSERT INTO address VALUES('Rua Raul Antunes 1566','Passo Fundo','RS','SUL', 554)
INSERT INTO address VALUES('Rua Treze 881','Santa Bárbara D''Oeste','SP','SUDESTE', 748)
INSERT INTO address VALUES('Rua Teodolino Costa 220','Gravataí','RS','SUL', 326)
INSERT INTO address VALUES('Rua Cariaca 1876','Rio de Janeiro','RJ','SUDESTE', 701)
INSERT INTO address VALUES('Rua Wanderley 1704','São Paulo','SP','SUDESTE', 885)
INSERT INTO address VALUES('Rua Jesuíno Antônio de Oliveira 1032','Ponta Grossa','PR','SUL', 597)
INSERT INTO address VALUES('Avenida Presidente Epitácio Pessoa 764','Paulo Afonso','BA','NORDESTE', 565)
INSERT INTO address VALUES('Rua Marechal Antônio Faustino 1987','Rio de Janeiro','RJ','SUDESTE', 702)
INSERT INTO address VALUES('Rua Olímpia 1954','Itaquaquecetuba','SP','SUDESTE', 375)
INSERT INTO address VALUES('Rua Antero Silva 712','Divinópolis','MG','SUDESTE', 232)
INSERT INTO address VALUES('Avenida Orlandinho Terzo de Emílio 1831','Araraquara','SP','SUDESTE', 33)
INSERT INTO address VALUES('Rua Maurício de Nassau 1816','Araçatuba','SP','SUDESTE', 26)
INSERT INTO address VALUES('Rua Odilon Correia 1066','Vitória da Conquista','BA','NORDESTE', 993)
INSERT INTO address VALUES('Avenida Nações 1589','Passos','MG','SUDESTE', 556)
INSERT INTO address VALUES('Travessa Santa Bárbara 337','Itabira','MG','SUDESTE', 358)
INSERT INTO address VALUES('Rua Rock Alexandre Prudêncio 1377','Criciúma','SC','SUL', 198)
INSERT INTO address VALUES('Rua Dezesseis 1596','Mauá','SP','SUDESTE', 487)
INSERT INTO address VALUES('Rua João-de-Barro 1261','Joinville','SC','SUL', 419)
INSERT INTO address VALUES('Rua 14 MP 234','Rio Claro','SP','SUDESTE', 669)
INSERT INTO address VALUES('Rua Vinte e Cinco 936','São Luís','MA','NORDESTE', 824)
INSERT INTO address VALUES('Rua Cláudio Manoel da Costa 343','Curitiba','PR','SUL', 226)
INSERT INTO address VALUES('Rua Cidade de Matipó 789','Poá','SP','SUDESTE', 591)
INSERT INTO address VALUES('Rua Quatorze 1546','Caraguatatuba','SP','SUDESTE', 148)
INSERT INTO address VALUES('Rua FL 8 1029','Goiânia','GO','CENTRO-OESTE', 314)
INSERT INTO address VALUES('Rua Acácia 1559','Jaboatão dos Guararapes','PE','NORDESTE', 395)
INSERT INTO address VALUES('Rua Bf 527','Cabo de Santo Agostinho','PE','NORDESTE', 112)
INSERT INTO address VALUES('Rua Salvador Barbosa 929','São Luís','MA','NORDESTE', 825)
INSERT INTO address VALUES('Rua Suíça 942','Guarulhos','SP','SUDESTE', 343)
INSERT INTO address VALUES('Rua Bruno Starke 149','Blumenau','SC','SUL', 98)
INSERT INTO address VALUES('Rua Pirineus 977','Goiânia','GO','CENTRO-OESTE', 315)
INSERT INTO address VALUES('Rua Manoel Rodrigues Roseira 1017','Osasco','SP','SUDESTE', 535)
INSERT INTO address VALUES('Rua Muller Campos 1208','São João de Meriti','RJ','SUDESTE', 792)
INSERT INTO address VALUES('Estrada da Lagoinha 1888','Queimados','RJ','SUDESTE', 625)
INSERT INTO address VALUES('Rua Jorge Maraccini Ponfílio 1421','São Paulo','SP','SUDESTE', 886)
INSERT INTO address VALUES('Avenida Central 626','Maracanaú','CE','NORDESTE', 479)
INSERT INTO address VALUES('Rua Treze 662','Petrolina','PE','NORDESTE', 575)
INSERT INTO address VALUES('Rua Goiania 258','Cachoeirinha','RS','SUL', 114)
INSERT INTO address VALUES('Quadra 812 Sul Avenida LO 21 692','Palmas','TO','NORTE', 543)
INSERT INTO address VALUES('Rua José Rodrigues Mendes 1496','Patos de Minas','MG','SUDESTE', 559)
INSERT INTO address VALUES('Praça do Imigrante 1674','Itatiba','SP','SUDESTE', 378)
INSERT INTO address VALUES('Rua 15 A 824','Manaus','AM','NORTE', 474)
INSERT INTO address VALUES('Rua João Mossin 1025','Sertãozinho','SP','SUDESTE', 912)
INSERT INTO address VALUES('Rua Valdecy Savignon 1095','Cachoeiro de Itapemirim','ES','SUDESTE', 117)
INSERT INTO address VALUES('Rua Xavier da Silva 1888','Foz do Iguaçu','PR','SUL', 280)
INSERT INTO address VALUES('Rua Zenaide Franco de Faria Mello 617','Mogi-Guaçu','SP','SUDESTE', 494)
INSERT INTO address VALUES('Rua Sebastião Fernandes da Silva 1798','Ferraz de Vasconcelos','SP','SUDESTE', 248)
INSERT INTO address VALUES('Avenida Rocha Pombo 625','Praia Grande','SP','SUDESTE', 617)
INSERT INTO address VALUES('Quadra 20 340','Planaltina de Goiás','GO','CENTRO-OESTE', 590)
INSERT INTO address VALUES('Rua Torres Tibagi 1687','São Paulo','SP','SUDESTE', 887)
INSERT INTO address VALUES('Rua Vinte e Dois 11','Rio de Janeiro','RJ','SUDESTE', 703)
INSERT INTO address VALUES('Rua Ângelo Borgo 1142','Vila Velha','ES','SUDESTE', 985)
INSERT INTO address VALUES('Rua Treze 148','Cuiabá','MT','CENTRO-OESTE', 210)
INSERT INTO address VALUES('Travessa Décio de Toledo Leite 910','Santo André','SP','SUDESTE', 764)
INSERT INTO address VALUES('Rua Padre Estanislau de Campos 1623','São Paulo','SP','SUDESTE', 888)
INSERT INTO address VALUES('Quadra 404 Sul Avenida NS 2 595','Palmas','TO','NORTE', 544)
INSERT INTO address VALUES('Rua Carlos de Souza Machado 367','Itumbiara','GO','CENTRO-OESTE', 386)
INSERT INTO address VALUES('Rua Três 1731','Várzea Grande','MT','CENTRO-OESTE', 977)
INSERT INTO address VALUES('Praça Jarbas Aratangy 168','São Paulo','SP','SUDESTE', 889)
INSERT INTO address VALUES('Rua Sétima 1088','Ituiutaba','MG','SUDESTE', 385)
INSERT INTO address VALUES('Avenida Voluntários da Pátria 1281','Londrina','PR','SUL', 444)
INSERT INTO address VALUES('Rua Vigília 776','Olinda','PE','NORDESTE', 529)
INSERT INTO address VALUES('Rua Pedro Xavier Martins 1274','Petrópolis','RJ','SUDESTE', 581)
INSERT INTO address VALUES('Rua Luís Alberto Favoreto 872','Maringá','PR','SUL', 485)
INSERT INTO address VALUES('Travessa do Carmo 183','Salvador','BA','NORDESTE', 740)
INSERT INTO address VALUES('Acesso Nove A 848','Porto Alegre','RS','SUL', 610)
INSERT INTO address VALUES('Rua Senador Pompeu 1666','Teresina','PI','NORDESTE', 946)
INSERT INTO address VALUES('Alameda Santa Luzia 661','Itu','SP','SUDESTE', 383)
INSERT INTO address VALUES('Rua José Coelho da Silva 1897','Rondonópolis','MT','CENTRO-OESTE', 712)
INSERT INTO address VALUES('Quadra QNP 13 Conjunto U 1515','Ceilândia','DF','CENTRO-OESTE', 174)
INSERT INTO address VALUES('Rua Guerra Junqueiro 1896','Belo Horizonte','MG','SUDESTE', 86)
INSERT INTO address VALUES('Rua Doze 926','Itapecerica da Serra','SP','SUDESTE', 368)
INSERT INTO address VALUES('Rua Gergelim 257','Fortaleza','CE','NORDESTE', 270)
INSERT INTO address VALUES('Estrada Antônio José de Oliveira 873','Apucarana','PR','SUL', 21)
INSERT INTO address VALUES('Rua Edward de Oliveira 903','Campo Grande','MS','CENTRO-OESTE', 137)
INSERT INTO address VALUES('Vila São Bernardino 1906','Fortaleza','CE','NORDESTE', 271)
INSERT INTO address VALUES('Rua Heitor de Almeida 1068','São Luís','MA','NORDESTE', 826)
INSERT INTO address VALUES('Avenida Henrique Fernandes 676','Birigüi','SP','SUDESTE', 93)
INSERT INTO address VALUES('Rua Vinte e Sete 215','Jacareí','SP','SUDESTE', 400)
INSERT INTO address VALUES('Rua Ana 1279','Macaé','RJ','SUDESTE', 455)
INSERT INTO address VALUES('Rua João Pinto 1468','Campo Grande','MS','CENTRO-OESTE', 138)
INSERT INTO address VALUES('Rua Maestro Marzagão 17','São Paulo','SP','SUDESTE', 890)
INSERT INTO address VALUES('Rua Sílvio Penteado Guimarães 1995','Santos','SP','SUDESTE', 770)
INSERT INTO address VALUES('Rua Sebastião da Rocha 1414','Maceió','AL','NORDESTE', 462)
INSERT INTO address VALUES('Avenida Lemos Monteiro 635','São Caetano do Sul','SP','SUDESTE', 775)
INSERT INTO address VALUES('Rua Jornalista José M. Ribeiro 1308','Lorena','SP','SUDESTE', 446)
INSERT INTO address VALUES('Rua Santa Ana 905','Gravataí','RS','SUL', 327)
INSERT INTO address VALUES('Rua das Palmeiras Reais 700','Araguaína','TO','NORTE', 28)
INSERT INTO address VALUES('Rua Jamésia 1789','Cotia','SP','SUDESTE', 193)
INSERT INTO address VALUES('Rua João Batista Barrozo Filho 1823','São Paulo','SP','SUDESTE', 891)
INSERT INTO address VALUES('Rua Rio Volga 397','Uberlândia','MG','SUDESTE', 963)
INSERT INTO address VALUES('Rua Teixeira dos Anjos 1243','Belo Horizonte','MG','SUDESTE', 87)
INSERT INTO address VALUES('Rodovia Comandante João Ribeiro de Barros 206','Tupã','SP','SUDESTE', 952)
INSERT INTO address VALUES('Rua Pires de Souto 1150','Nova Iguaçu','RJ','SUDESTE', 522)
INSERT INTO address VALUES('Avenida Montemagno 725','São Paulo','SP','SUDESTE', 892)
INSERT INTO address VALUES('Rua Eurico Castro Monteiro 273','Juiz de Fora','MG','SUDESTE', 423)
INSERT INTO address VALUES('Rua Peppino Agrelli 384','São José do Rio Preto','SP','SUDESTE', 800)
INSERT INTO address VALUES('Rua Haroldo Barbosa 798','Presidente Prudente','SP','SUDESTE', 621)
INSERT INTO address VALUES('Rua Doutor Manoel Borba 1417','Carpina','PE','NORDESTE', 157)
INSERT INTO address VALUES('Alameda Ana Nery 869','Corumbá','MS','CENTRO-OESTE', 189)
INSERT INTO address VALUES('Rua Padre Faustino 254','São Paulo','SP','SUDESTE', 893)
INSERT INTO address VALUES('Rua Jaudat Rachid 887','Colatina','ES','SUDESTE', 178)
INSERT INTO address VALUES('Avenida Nelo Pisani 1511','Mococa','SP','SUDESTE', 489)
INSERT INTO address VALUES('Rua 31 288','Goiânia','GO','CENTRO-OESTE', 316)
INSERT INTO address VALUES('Rua Curitiba 1729','Cabo Frio','RJ','SUDESTE', 113)
INSERT INTO address VALUES('Rua Marquês de Abrantes 469','Rio de Janeiro','RJ','SUDESTE', 704)
INSERT INTO address VALUES('Rua Tupiniquins 961','Recife','PE','NORDESTE', 648)
INSERT INTO address VALUES('Quadra QNG 24 817','Taguatinga','DF','CENTRO-OESTE', 936)
INSERT INTO address VALUES('Rua José Boanerges Cesar 75','Rio de Janeiro','RJ','SUDESTE', 705)
INSERT INTO address VALUES('Rua Bela Vista I 1345','Cariacica','ES','SUDESTE', 156)
INSERT INTO address VALUES('Rua Martim Afonso de Souza 856','Ribeirão Preto','SP','SUDESTE', 665)
INSERT INTO address VALUES('Rua Vista Atlântica 1495','Vitória','ES','SUDESTE', 990)
INSERT INTO address VALUES('Rua V 1748','Fortaleza','CE','NORDESTE', 272)
INSERT INTO address VALUES('Rua Benedito Alves Bandeira 159','Belém','PA','NORTE', 66)
INSERT INTO address VALUES('Rua Barra do Piraí 1573','Fortaleza','CE','NORDESTE', 273)
INSERT INTO address VALUES('Avenida Clemente Teodoro da Silva 977','Itajubá','MG','SUDESTE', 364)
INSERT INTO address VALUES('Rua Vereador Tomás da Costa 514','Atibaia','SP','SUDESTE', 40)
INSERT INTO address VALUES('Rua Triângulo Mineiro 397','Joinville','SC','SUL', 420)
INSERT INTO address VALUES('Rua Um 985','Almirante Tamandaré','PR','SUL', 6)
INSERT INTO address VALUES('Travessa Julceia 1920','Niterói','RJ','SUDESTE', 514)
INSERT INTO address VALUES('Travessa Quinto Império 464','São Paulo','SP','SUDESTE', 894)
INSERT INTO address VALUES('Quadra Quadra 125 1204','Luziânia','GO','CENTRO-OESTE', 452)
INSERT INTO address VALUES('Rua Mário Spineli 1118','Cuiabá','MT','CENTRO-OESTE', 211)
INSERT INTO address VALUES('Rua Alexandre Dumas 766','São Paulo','SP','SUDESTE', 895)
INSERT INTO address VALUES('Rua das Pitangueiras 1157','São Bernardo do Campo','SP','SUDESTE', 774)
INSERT INTO address VALUES('Rua Jasmin 770','Rio de Janeiro','RJ','SUDESTE', 706)
INSERT INTO address VALUES('Rua Doze de Janeiro 213','Japeri','RJ','SUDESTE', 403)
INSERT INTO address VALUES('Rua Narcísio Maximiliano da Silva 1541','Blumenau','SC','SUL', 99)
INSERT INTO address VALUES('Rua José M. Carvalho 1655','São João Del Rei','MG','SUDESTE', 794)
INSERT INTO address VALUES('Rua Vinte e Nove 1177','Itabira','MG','SUDESTE', 359)
INSERT INTO address VALUES('Quadra EQNP 16/20 Bloco F 538','Ceilândia','DF','CENTRO-OESTE', 175)
INSERT INTO address VALUES('Rua Rouxinol 135','Umuarama','PR','SUL', 969)
INSERT INTO address VALUES('Rua Bernardo Guimarães 754','Lages','SC','SUL', 429)
INSERT INTO address VALUES('Rua Nair Marques de Souza 951','Taboão da Serra','SP','SUDESTE', 933)
INSERT INTO address VALUES('Rua Silvestre José Dantas 321','São Paulo','SP','SUDESTE', 896)
INSERT INTO address VALUES('Rua Aldorando José de Souza 1184','Uberlândia','MG','SUDESTE', 964)
INSERT INTO address VALUES('Praça Doutor João Pereira Monteiro Júnior 42','São Paulo','SP','SUDESTE', 897)
INSERT INTO address VALUES('Praça São Lázaro 123','Salvador','BA','NORDESTE', 741)
INSERT INTO address VALUES('Rua Rio Vermelho 1895','Recife','PE','NORDESTE', 649)
INSERT INTO address VALUES('Rua 113 242','Fortaleza','CE','NORDESTE', 274)
INSERT INTO address VALUES('Rua Edgard Werneck 1294','Rio de Janeiro','RJ','SUDESTE', 707)
INSERT INTO address VALUES('Rua do Açafrão 1664','Olinda','PE','NORDESTE', 530)
INSERT INTO address VALUES('Rua Edson Brasil 137','Fortaleza','CE','NORDESTE', 275)
INSERT INTO address VALUES('Rua Fernão Dias 273','Guaratinguetá','SP','SUDESTE', 333)
INSERT INTO address VALUES('Rua Francisco Casamassa 310','Franco da Rocha','SP','SUDESTE', 292)
INSERT INTO address VALUES('Quadra SQN 403 1390','Brasília','DF','CENTRO-OESTE', 108)
INSERT INTO address VALUES('Rua F 1027','Duque de Caxias','RJ','SUDESTE', 239)
INSERT INTO address VALUES('Rua Ernesto Barreto 211','Campinas','SP','SUDESTE', 131)
INSERT INTO address VALUES('Rua Sírius 965','Belo Horizonte','MG','SUDESTE', 88)
INSERT INTO address VALUES('Rua Alagoas 1047','Catanduva','SP','SUDESTE', 165)
INSERT INTO address VALUES('Rua Advogado João Alves da Cunha Lima 644','Bragança Paulista','SP','SUDESTE', 104)
INSERT INTO address VALUES('Rua Flande 978','Rio de Janeiro','RJ','SUDESTE', 708)
INSERT INTO address VALUES('Rua Pirangi 802','Goiânia','GO','CENTRO-OESTE', 317)
INSERT INTO address VALUES('Rua Roberto Simonsen 180','Nova Iguaçu','RJ','SUDESTE', 523)
INSERT INTO address VALUES('Rua Ingá 1953','Ribeirão Preto','SP','SUDESTE', 666)
INSERT INTO address VALUES('Quadra QNP 26 Conjunto S 1650','Ceilândia','DF','CENTRO-OESTE', 176)
INSERT INTO address VALUES('Rua Vinte e Um de Abril 181','Goiânia','GO','CENTRO-OESTE', 318)
INSERT INTO address VALUES('Quadra SQN 306 Bloco G 443','Brasília','DF','CENTRO-OESTE', 109)
INSERT INTO address VALUES('Rua João Meurer 668','Jaraguá do Sul','SC','SUL', 406)
INSERT INTO address VALUES('Rua Judite Danon 1142','Nova Iguaçu','RJ','SUDESTE', 524)
INSERT INTO address VALUES('Rua Flores de Maio 378','Queimados','RJ','SUDESTE', 626)
INSERT INTO address VALUES('Rua Doutor Carlos Carvalho Rosa 515','Birigüi','SP','SUDESTE', 94)
INSERT INTO address VALUES('Rua Doze de Outubro 346','Recife','PE','NORDESTE', 650)
INSERT INTO address VALUES('Travessa Saturnino de Brito 448','Santo André','SP','SUDESTE', 765)
INSERT INTO address VALUES('Rua Atalanta 509','São Paulo','SP','SUDESTE', 898)
INSERT INTO address VALUES('Rua Argélia 1542','São Leopoldo','RS','SUL', 814)
INSERT INTO address VALUES('Rua Santa Maria Goretti 956','Santo André','SP','SUDESTE', 766)
INSERT INTO address VALUES('Rua Maria dos Santos Ramos 171','Palhoça','SC','SUL', 537)
INSERT INTO address VALUES('Praça C-0231 758','Goiânia','GO','CENTRO-OESTE', 319)
INSERT INTO address VALUES('Rua W 14 1365','Goiânia','GO','CENTRO-OESTE', 320)
INSERT INTO address VALUES('Rua Joaquim Carneiro da Silva 21','Recife','PE','NORDESTE', 651)
INSERT INTO address VALUES('Rua Vinte 339','São Luís','MA','NORDESTE', 827)
INSERT INTO address VALUES('Quadra SEPS 713/913 1566','Brasília','DF','CENTRO-OESTE', 110)
INSERT INTO address VALUES('Passagem Wilson Brito 199','Belém','PA','NORTE', 67)
INSERT INTO address VALUES('Travessa Augusto Guedes dos Santos 1584','Jaboatão dos Guararapes','PE','NORDESTE', 396)
INSERT INTO address VALUES('Rua São Lucas 1187','Apucarana','PR','SUL', 22)
INSERT INTO address VALUES('Rua João Tonalezzi 329','Ferraz de Vasconcelos','SP','SUDESTE', 249)
INSERT INTO address VALUES('Beco Barcelos 165','Porto Alegre','RS','SUL', 611)
INSERT INTO address VALUES('Avenida Principal 1363','Gravataí','RS','SUL', 328)
INSERT INTO address VALUES('Rua Zoroastro Alves de Souza 1719','Marília','SP','SUDESTE', 482)
INSERT INTO address VALUES('Rua dos Estudantes 652','Sumaré','SP','SUDESTE', 927)
INSERT INTO address VALUES('Rua Sidrônio Andrade 1453','Lages','SC','SUL', 430)
INSERT INTO address VALUES('Rua Vassouras 1061','São João de Meriti','RJ','SUDESTE', 793)
INSERT INTO address VALUES('Rua Lauro Sodré 800','Nilópolis','RJ','SUDESTE', 510)
INSERT INTO address VALUES('Rua Joventina Maria de Santana 1301','Igarassu','PE','NORDESTE', 350)
INSERT INTO address VALUES('Travessa Um 1277','Valinhos','SP','SUDESTE', 974)
INSERT INTO address VALUES('Rua Eleutério Varela 1985','São Luís','MA','NORDESTE', 828)
INSERT INTO address VALUES('Rua Sargento Wolf 216','Marabá','PA','NORTE', 476)
INSERT INTO address VALUES('Rua Turivara 32','Jacareí','SP','SUDESTE', 401)
INSERT INTO address VALUES('Rua H 471','Juiz de Fora','MG','SUDESTE', 424)
INSERT INTO address VALUES('Rua 5 Unidade 203 798','Goiânia','GO','CENTRO-OESTE', 321)
INSERT INTO address VALUES('Travessa Aracy Alvellos Eudociak 1266','Campo Grande','MS','CENTRO-OESTE', 139)
INSERT INTO address VALUES('Rua Andreia Pacini 40','São Paulo','SP','SUDESTE', 899)
INSERT INTO address VALUES('Rua Frei Domingos 128','Palmeira dos Índios','AL','NORDESTE', 546)
INSERT INTO address VALUES('Beco São Francisco 532','Manaus','AM','NORTE', 475)
INSERT INTO address VALUES('Rua Fideralina Gomes de Almeida 1904','Taboão da Serra','SP','SUDESTE', 934)
INSERT INTO address VALUES('Avenida Cascavel 964','Goiânia','GO','CENTRO-OESTE', 322)
INSERT INTO address VALUES('Rua Doutor Alexandre Ferreira 1644','São Paulo','SP','SUDESTE', 900)
INSERT INTO address VALUES('Rua Francisco Cipriano de Paula 60','Mossoró','RN','NORDESTE', 504)
INSERT INTO address VALUES('Rua Dez 1790','Campo Largo','PR','SUL', 140)
INSERT INTO address VALUES('Rua Maria Elvira Paiva 1367','São Gonçalo','RJ','SUDESTE', 787)
INSERT INTO address VALUES('Rua Antônio da Cunha Filho 1958','Araxá','MG','SUDESTE', 37)
INSERT INTO address VALUES('Avenida Joaquim Teixeira Alves 1345','Dourados','MS','CENTRO-OESTE', 234)
INSERT INTO address VALUES('Rua 4 1265','Fortaleza','CE','NORDESTE', 276)
INSERT INTO address VALUES('Praça Obrandina Guidini 818','São Paulo','SP','SUDESTE', 901)
INSERT INTO address VALUES('Rua José Henrique Batista 1763','Barra Mansa','RJ','SUDESTE', 49)
INSERT INTO address VALUES('Rua Seis 558','Suzano','SP','SUDESTE', 930)
INSERT INTO address VALUES('Rua José Mafra 1796','Blumenau','SC','SUL', 100)
INSERT INTO address VALUES('Rua Dois 1375','Cuiabá','MT','CENTRO-OESTE', 212)
INSERT INTO address VALUES('Rua Água Branca 1221','Guarulhos','SP','SUDESTE', 344)
INSERT INTO address VALUES('Rua F-2 1428','Belo Horizonte','MG','SUDESTE', 89)
INSERT INTO address VALUES('Rua Major Manoel Cândido 1725','Poços de Caldas','MG','SUDESTE', 593)
INSERT INTO address VALUES('Rua Granito 314','Olinda','PE','NORDESTE', 531)
INSERT INTO address VALUES('Avenida José Jerônimo 876','Araraquara','SP','SUDESTE', 34)
INSERT INTO address VALUES('Praça das Bandeiras 1607','Ribeirão das Neves','MG','SUDESTE', 657)
INSERT INTO address VALUES('Rua T 1518','Fortaleza','CE','NORDESTE', 277)
INSERT INTO address VALUES('Rua Princesa Isabel 1079','Volta Redonda','RJ','SUDESTE', 999)
INSERT INTO address VALUES('Rua Gambia 1936','Embu','SP','SUDESTE', 241)
INSERT INTO address VALUES('Rua das Orquídeas 1940','Jaboatão dos Guararapes','PE','NORDESTE', 397)
INSERT INTO address VALUES('Rua Engenheiro Reginaldo Arcuri 765','Juiz de Fora','MG','SUDESTE', 425)
INSERT INTO address VALUES('Rua Setenta e Oito 1184','Mauá','SP','SUDESTE', 488)
INSERT INTO address VALUES('Viela Navegantes 359','Guarulhos','SP','SUDESTE', 345)
INSERT INTO address VALUES('Rua Cheroke 1319','Mogi-Mirim','SP','SUDESTE', 496)
INSERT INTO address VALUES('Rua Professor Kydd James Galliano 190','Curitiba','PR','SUL', 227)
INSERT INTO address VALUES('Rua Galeão Carvalhal 1053','Santo André','SP','SUDESTE', 767)
INSERT INTO address VALUES('Rua Caldas 1916','Betim','MG','SUDESTE', 92)
INSERT INTO address VALUES('Rua Botucatu 328','Salto','SP','SUDESTE', 717)
INSERT INTO address VALUES('Alameda Sargento Rolembach 765','Foz do Iguaçu','PR','SUL', 281)
INSERT INTO address VALUES('Praça Córsega 712','Belo Horizonte','MG','SUDESTE', 90)
