USE oltp_commerce
GO

INSERT INTO category VALUES('LIVROS')
INSERT INTO category VALUES('DVDS')
INSERT INTO category VALUES('GAMES')
INSERT INTO category VALUES('CELULARES')
INSERT INTO category VALUES('INFORMATICA')
INSERT INTO category VALUES('TV E AUDIO')
INSERT INTO category VALUES('ELETRODOMESTICOS')
INSERT INTO category VALUES('MOVEIS')
INSERT INTO category VALUES('PASSAGENS')
GO
