CREATE PROCEDURE camel_case AS

DECLARE c_names CURSOR FOR
SELECT id_product, name FROM st_product

DECLARE @IDPRODUCT INT,
		@WORD VARCHAR(30),
		@STRINGTOTAL VARCHAR(500),
		@START INT,
		@FINISH INT

OPEN c_names
FETCH NEXT FROM c_names INTO @IDPRODUCT, @WORD

WHILE @@FETCH_STATUS = 0

BEGIN 
	SET @WORD = LOWER(@WORD)
	SET @START = 2
	SET @FINISH = LEN(@WORD)
	SET @STRINGTOTAL = UPPER(LEFT(@WORD, 1))

	WHILE @START <= @FINISH
		
		BEGIN
			IF SUBSTRING(@WORD, @START, 1) = ' '
				BEGIN
					SELECT @START = @START + 1
					SELECT @STRINGTOTAL = @STRINGTOTAL + ' ' + UPPER(SUBSTRING(@WORD,@START,1))
				END
			ELSE
				BEGIN
					SELECT @STRINGTOTAL = @STRINGTOTAL + SUBSTRING(@WORD,@START,1)
				END

			SELECT @START = @START + 1
		END

		UPDATE st_product SET name = @STRINGTOTAL
		WHERE id_product = @IDPRODUCT

		FETCH NEXT FROM c_names INTO @IDPRODUCT, @WORD
END
